/* Group trapezoid/ribbon: one exact horizontal interval per source process.
 * Connecting endpoints is a visual grouping envelope, never an execution interval. */
RANKED.bands=[];
function groupBand(host,entries,onPick,{title='分组梯形时间带'}={}){
 const sorted=entries.slice().sort((a,b)=>a.b-b.b||a.e-b.e||a.id.localeCompare(b.id));if(!sorted.length)return;
 const box=elt('div',undefined,'group-band'),heading=elt('h4',title),explain=elt('p',`全部 ${sorted.length} 个实例各对应一条横线。左侧开始轴、右侧结束轴分别定位真实时间；两轴刻度相同，但并非一根连续横轴。每条横线连接同一实例两端，横线长度不代表耗时；真实耗时见实例详情。按开始时间排列，轮廓仅表示分组，不表示持续执行。默认压缩较长时间间隔，// 为折叠标记；展开明细可查每段真实开始/结束、间隔和压缩比例，取消折叠可回到原始时间。颜色对应本页记录的物理设备；本例仅 DCU1。`),controls=elt('div',undefined,'controls');
 const rowsButton=elt('button','展开逐行（36 px / 实例）'),plus=elt('button','时间轴放大'),minus=elt('button','时间轴缩小'),reset=elt('button','全组时间范围'),axisButton=elt('button','切换为单轴'),foldButton=elt('button','取消时间折叠'),state=elt('p',undefined,'chart-state'),scroller=elt('div',undefined,'band-scroll'),canvas=elt('canvas'),tip=elt('p','点击横线进入对应实例；Shift + 滚轮可缩放时间轴，拖动可平移。起止双轴中的横线仅连接身份；切换单轴可按线长看时长。','chart-tooltip');canvas.setAttribute('aria-label',title);canvas.tabIndex=0;scroller.append(canvas);controls.append(rowsButton,axisButton,foldButton,plus,minus,reset);box.append(heading,explain,controls,state,scroller,tip);host.append(box);
 let rowStart=0;const pageSize=300;const rowPrev=elt('button','上一批实例'),rowNext=elt('button','下一批实例');controls.append(rowPrev,rowNext);rowPrev.onclick=()=>{rowStart=Math.max(0,rowStart-pageSize);draw();};rowNext.onclick=()=>{rowStart=Math.min(Math.floor((sorted.length-1)/pageSize)*pageSize,rowStart+pageSize);draw();};
 const min=Math.min(...sorted.map(i=>i.b)),max=Math.max(...sorted.map(i=>i.e)),padding=Math.max(1,Math.round((max-min)*.025));let view=[min-padding,max+padding],expanded=false,paired=true,folded=true,width=0,height=0,rowH=0,selected=-1,drag=null;const left=240,right=40,top=54,bottom=30,base=min;
 const boundaries=[...new Set(sorted.flatMap(i=>[i.b,i.e]))].sort((a,b)=>a-b),durations=sorted.map(i=>i.e-i.b).sort((a,b)=>a-b),cap=Math.max(1,2*durations[Math.floor(durations.length/2)]),segments=[];let cumulative=0;
 for(let j=1;j<boundaries.length;j++){const b=boundaries[j-1],e=boundaries[j],weight=Math.min(e-b,cap);segments.push({b,e,weight,start:cumulative,compressed:weight<e-b});cumulative+=weight;}
 const folds=segments.filter(s=>s.compressed),foldInfo=elt('details'),foldSummary=elt('summary',`折叠区间 ${folds.length} 段：查看全部真实起止、间隔与显示权重`),foldTable=elt('div');foldInfo.append(foldSummary,foldTable);box.append(foldInfo);foldInfo.ontoggle=()=>{if(foldInfo.open&&!foldTable.childNodes.length)tableView(foldTable,folds.map(s=>({begin_ns:absolute(s.b),end_ns:absolute(s.e),real_interval_ns:String(s.e-s.b),display_weight:String(s.weight),compression_factor:((s.e-s.b)/s.weight).toFixed(3)})),['begin_ns','end_ns','real_interval_ns','display_weight','compression_factor'],showDetails);};
 function project(t){if(!folded)return t-min;if(t<min)return t-min;if(t>=max)return cumulative+t-max;let lo=0,hi=segments.length;while(lo<hi){const mid=(lo+hi)>>1;if(segments[mid].e<=t)lo=mid+1;else hi=mid;}const s=segments[lo];return s.start+(t-s.b)/(s.e-s.b)*s.weight;}
 function inverse(v){if(!folded)return min+v;if(v<0)return min+v;if(v>=cumulative)return max+v-cumulative;let lo=0,hi=segments.length;while(lo<hi){const mid=(lo+hi)>>1;if(segments[mid].start+segments[mid].weight<=v)lo=mid+1;else hi=mid;}const s=segments[lo];return s.b+(v-s.start)/s.weight*(s.e-s.b);}
 const sourceExtent=[min,max];view=sourceExtent.slice();function x(t,side='b'){const available=width-left-right,fraction=(project(t)-project(view[0]))/(project(view[1])-project(view[0]));if(!paired)return left+fraction*available;const half=(available-80)/2,begin=left+(side==='e'?half+80:0);return begin+Math.max(0,Math.min(1,fraction))*half;}function y(i){return top+(i+.5)*rowH;}
 function draw(){const visibleRows=expanded?sorted.slice(rowStart,rowStart+pageSize):sorted;rowPrev.disabled=!expanded||rowStart===0;rowNext.disabled=!expanded||rowStart+pageSize>=sorted.length;width=Math.max(1040,scroller.clientWidth);rowH=expanded?36:Math.min(34,Math.max(.25,(590-top-bottom)/visibleRows.length));height=Math.max(240,Math.ceil(top+bottom+rowH*visibleRows.length));canvas.width=width;canvas.height=height;canvas.style.width=width+'px';canvas.style.height=height+'px';const c=canvas.getContext('2d');c.fillStyle='#0b1728';c.fillRect(0,0,width,height);c.font='12px system-ui';c.fillStyle='#bbd0ec';const avail=width-left-right,half=(avail-80)/2;const axes=paired?[{side:'b',start:left,length:half,label:folded?'开始时间 / ms（折叠左轴）':'开始时间 / ms（左轴）'},{side:'e',start:left+half+80,length:half,label:folded?'结束时间 / ms（折叠右轴）':'结束时间 / ms（右轴）'}]:[{side:'b',start:left,length:avail,label:folded?'折叠单轴：时间 / ms；线长不按原比例':'原始单轴：时间 / ms；线长=执行时长'}];
  for(const axis of axes){c.fillStyle='#bbd0ec';c.fillText(axis.label,axis.start,17);for(let k=0;k<=3;k++){const t=inverse(project(view[0])+(project(view[1])-project(view[0]))*k/3),xx=axis.start+axis.length*k/3;c.strokeStyle='#2a3f5a';c.beginPath();c.moveTo(xx,40);c.lineTo(xx,height-bottom);c.stroke();c.fillStyle='#b8cce7';c.fillText(((t-base)/1e6).toFixed(view[1]-view[0]<1e6?6:3),Math.min(axis.start+axis.length-78,xx),34);}}
  if(paired){c.fillStyle='#18314b';c.fillRect(left+half+5,top,70,height-top-bottom);c.fillStyle='#b7d4ef';c.fillText('独立双轴',left+half+10,34);}
  if(folded){for(const axis of axes)for(const f of folds){if(f.e<=view[0]||f.b>=view[1])continue;const xx=x((f.b+f.e)/2,axis.side);c.strokeStyle='#dcaddf';c.lineWidth=1.5;c.beginPath();c.moveTo(xx-4,42);c.lineTo(xx,36);c.moveTo(xx+1,42);c.lineTo(xx+5,36);c.stroke();}}
  c.save();c.beginPath();c.rect(left,top,width-left-right,height-top-bottom);c.clip();
  // Boundaries go through every actual endpoint. No fabricated straight edges.
  c.beginPath();visibleRows.forEach((i,j)=>j?c.lineTo(x(i.b),y(j)):c.moveTo(x(i.b),y(j)));for(let j=visibleRows.length-1;j>=0;j--)c.lineTo(x(visibleRows[j].e,'e'),y(j));c.closePath();c.fillStyle='#76b4ea25';c.fill();
  for(const side of ['b','e']){c.beginPath();visibleRows.forEach((i,j)=>j?c.lineTo(x(i[side],side),y(j)):c.moveTo(x(i[side],side),y(j)));c.lineWidth=1.2;c.strokeStyle=side==='b'?'#668fb7':'#a3cde7';c.stroke();}
  visibleRows.forEach((i,j)=>{const yy=y(j);if(i.e<view[0]||i.b>view[1])return;const xb=x(i.b,'b'),xe=x(i.e,'e');c.strokeStyle=String(i.rank)==='0'?'#64b5ff':'#f3bd6d';c.lineWidth=j+(expanded?rowStart:0)===selected?5:expanded?3:Math.max(.18,Math.min(2,rowH*.45));c.beginPath();const hasFold=folded&&folds.some(f=>f.b<i.e&&f.e>i.b);const showBreak=hasFold&&(expanded||visibleRows.length<=25||j+(expanded?rowStart:0)===selected)&&xe-xb>40;if(showBreak){const mid=(xb+xe)/2;c.moveTo(xb,yy);c.lineTo(mid-7,yy);c.moveTo(mid+7,yy);c.lineTo(xe,yy);c.stroke();c.beginPath();c.moveTo(mid-6,yy+5);c.lineTo(mid-1,yy-5);c.moveTo(mid+1,yy+5);c.lineTo(mid+6,yy-5);}else{c.moveTo(xb,yy);c.lineTo(xe,yy);}c.stroke();if(expanded||visibleRows.length<=25||j+(expanded?rowStart:0)===selected){c.fillStyle=c.strokeStyle;c.beginPath();c.arc(xb,yy,2.4,0,Math.PI*2);c.arc(xe,yy,2.4,0,Math.PI*2);c.fill();if(xe-xb>110){c.fillStyle='#d9eaff';c.font='11px system-ui';c.fillText(duration(i.e-i.b),xb+5,yy-5);}}});c.restore();
  const every=expanded||visibleRows.length<=25?1:Math.ceil(visibleRows.length/14);for(let j=0;j<visibleRows.length;j++){if(j%every!==0&&j!==visibleRows.length-1&&j+(expanded?rowStart:0)!==selected)continue;const i=visibleRows[j];c.font=expanded?'11px system-ui':'12px system-ui';c.fillStyle=String(i.rank)==='0'?'#9dcfff':'#f2c98f';c.fillText(`#${j+1+(expanded?rowStart:0)} ${i.label}`.slice(0,34),8,y(j)+4);}
  state.textContent=`${folded?'折叠开启：// 表示压缩区间；每段真实起止/间隔可在下方展开查看。':'未折叠。'}${paired?'起止双轴：横线长度不代表时长。':folded?'折叠单轴：线长不按原时间比例。':'原始单轴：横线长度按真实时长缩放。'}全组横线 ${visibleRows.length} / ${entries.length}；排序：实际开始、结束、源 ID；基准 ${absolute(base)} ns；当前 [${absolute(view[0])}, ${absolute(view[1])})。${expanded?'每行 36 px；每批最多 300 行，可前后翻批，避免超高 Canvas 丢图。':'全组概览压缩纵向间距；可展开逐行，所有实例均保留。'}`;
 }
 function setView(b,e){if(!Number.isSafeInteger(b)||!Number.isSafeInteger(e)||e<=b)throw Error('invalid band viewport');view=[b,e];draw();}
 function zoom(f,anchor=.5){const span=view[1]-view[0],size=Math.max(1,Math.round(span*f)),pivot=view[0]+Math.round(span*anchor),b=pivot-Math.round(size*anchor);setView(b,b+size);}
 function pick(i){selected=Math.max(0,Math.min(sorted.length-1,i));draw();const item=sorted[selected];tip.textContent=`#${selected+1} ${item.label}；开始 ${absolute(item.b)} ns；结束 ${absolute(item.e)} ns；时长 ${duration(item.e-item.b)}。`;if(onPick)onPick(item);return item;}
 canvas.onmousemove=e=>{if(drag)return;const j=Math.floor((e.offsetY-top)/rowH);if(j<0||j>=sorted.length)return;const i=sorted[j+(expanded?rowStart:0)];if(!i)return;tip.textContent=`#${j+1} ${i.label}；[${absolute(i.b)}, ${absolute(i.e)})；${duration(i.e-i.b)}；点击定位实例。`;};canvas.onwheel=e=>{if(e.ctrlKey||e.shiftKey){e.preventDefault();zoom(Math.exp(e.deltaY*.001),Math.max(0,Math.min(1,(e.offsetX-left)/(width-left-right))));}};canvas.onpointerdown=e=>{drag={x:e.clientX,view:view.slice()};canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>4){const delta=Math.round(dx/(width-left-right)*(drag.view[1]-drag.view[0]));setView(drag.view[0]-delta,drag.view[1]-delta);}else pick(Math.floor((e.offsetY-top)/rowH)+(expanded?rowStart:0));drag=null;};axisButton.onclick=()=>{paired=!paired;axisButton.textContent=paired?'切换为单轴':'切换为起止双轴（梯形）';draw();};foldButton.onclick=()=>{folded=!folded;foldButton.textContent=folded?'取消时间折叠':'启用时间折叠';draw();};rowsButton.onclick=()=>{expanded=!expanded;rowsButton.textContent=expanded?'折回全组概览':'展开逐行（36 px / 实例）';draw();};plus.onclick=()=>zoom(.5);minus.onclick=()=>zoom(2);reset.onclick=()=>setView(...sourceExtent);
 const api={entries:sorted,draw,pick,setView,zoom,get view(){return view.slice();},folds,cap,get folded(){return folded;},project,inverse,get paired(){return paired;},get expanded(){return expanded;},get rowHeight(){return rowH;},get selected(){return selected;},element:box};RANKED.bands.push(api);draw();return api;
}
