/* Rankings navigate the complete retained evidence; they do not reclassify R09. */
const device=D.scope.physical_device_id,pmap=new Map(D.processes.map(p=>[p.process,p]));
const K=D.high?.kernels||D.kernels,C=D.concurrency,H=D.high;
const kmap=groupRows(K,k=>k.process),samples=(H?.samples||C.samples).map((r,i)=>({b:offset(r.t),v:Number(r.mean),eligible:r.eligible,row:r,table:'live_utilization_aligned',label:`原始采样 #${i}`})).sort((a,b)=>a.b-b.b);
const liveLane=()=>({label:`DCU${device} 原始 SE 利用率`,subtitle:'● 合格点；× 对齐不合格',points:true,items:samples,device});
const marker=p=>({label:`DCU${device} Process`,subtitle:`forward ${p.forward} / L${p.layer}`,items:[interval(p,'process_timeline','b','e',p.stage)],color:'#f3bd6d',device});
const bandEntries=ms=>ms.map((p,index)=>({b:offset(p.b),e:offset(p.e),id:p.process||p.id,rank:String(device),index,p,label:p.process?`F${p.forward} L${p.layer} ${p.stage}`:p.id}));
const normGroups=name=>D.rankings[name].map(g=>({...g,name:g.key,score:Number(g.score_ns),members:g.members.map(id=>pmap.get(id))}));
function sourceDetail(table,row,extra={}){showDetails({table,retained_archives:D.provenance,original_retained_row:row,...extra});}
function choose(card,g,callback){const controls=elt('div',undefined,'controls'),select=elt('select');select.setAttribute('aria-label','组内实例');g.members.forEach((p,i)=>{const option=elt('option',`${i+1}/${g.members.length} · ${p.process||p.id} · ${duration(offset(p.e)-offset(p.b))}`);option.value=String(i);select.append(option);});controls.append(elt('label','组内实例'),select);card.append(controls);const body=elt('div');card.append(body);function draw(){body.replaceChildren();callback(body,g.members[Number(select.value)]);}select.onchange=draw;draw();return {selectIndex(i){select.value=String(i);draw();}};}
function tableSection(host,title,rows,fields,table){const d=elt('details'),target=elt('div',undefined,'source-table');d.append(elt('summary',`${title}（完整 ${rows.length} 条；搜索 / 分页）`),target);d.ontoggle=()=>{if(d.open&&!target.childNodes.length)tableView(target,rows,fields,r=>sourceDetail(table,r));};host.append(d);}
function processPlot(body,p,extraLanes=[]){const ks=kmap.get(p.process)||[],lanes=[marker(p)];for(const [queue,rows] of groupRows(ks,k=>k.queue))lanes.push({label:`严格归属 kernel · queue ${queue}`,subtitle:`${rows.length} 条，不重复计数`,items:rows.map(k=>interval(k,'kernel_timeline','b','e',k.n)),color:'#73bfde',device});if(!ks.length)lanes.push({label:'严格归属 kernel',subtitle:'无归属记录；不是设备 idle',items:[],device});lanes.push(...extraLanes,liveLane());const b=Math.min(offset(p.b),...ks.map(k=>offset(k.b))),e=Math.max(offset(p.e),...ks.map(k=>offset(k.e)));const pad=Math.max(1,Math.round((e-b)*.04));chart(body,lanes,[b-pad,e+pad],{title:p.process});return ks;}
function renderHigh(){const groups=normGroups('high'),hm=new Map(H.processes.map(p=>[p.process,p])),am=groupRows(H.attachments,a=>a.process_range),lm=new Map(H.process_live.map(p=>[p.process_range,p])),om=new Map(H.opportunities.map(p=>[p.process_range,p]));
 const cat=catalog('high','高延迟 Process：分组排名时间线','按 phase + stage 分组；每个实例以实际起止横线组成梯形。组内最长实例先显示，可通过横线或下拉框查看任何实例及其硬件证据。',groups,(card,g)=>{card.append(elt('p',`${g.members.length} 个已标记实例；观测时长总和 ${duration(g.score)}。总和用于导航排序，存在重叠时不可作为 Request 的耗时归因。`));let chooser;groupBand(card,bandEntries(g.members),i=>chooser?.selectIndex(i.index));chooser=choose(card,g,(body,p)=>{const high=hm.get(p.process),attach=am.get(p.process)||[],live=lm.get(p.process),opp=om.get(p.process);const families=new Set(attach.map(a=>a.matched_kernel_family).filter(Boolean));const hardware=H.hardware.filter(r=>r.event_id===p.event&&r.stage===p.stage&&families.has(r.matched_kernel_family));const kernels=processPlot(body,p);
 const box=elt('div',undefined,'metric-box');box.append(elt('p',`已封存高延迟列表中的原始分类：${high.evidence}；${duration(offset(p.e)-offset(p.b))}。本次保留全部 128 条，不另设 p95 或重写阈值。`));box.append(elt('p',`R07 观测 SE 均值 ${live?.status==='observed'?live.mean_se_active_cu_pct+'%':live?.status||'unavailable'}；合格采样数 ${live?.sample_count??'unavailable'}；对齐不确定度 ${live?.maximum_alignment_uncertainty_ns??'unavailable'} ns。`));box.append(elt('p',`严格归属 kernel ${kernels.length} 条；精确 event + stage + attachment family 匹配硬件行 ${hardware.length} 条。${hardware.length?'下列属性来自 R08 重放，不能作为本轴的运行耗时或因果证明。':'该实例没有精确匹配的 R08 硬件行：unavailable；不借用同名其他 Process 的数据。'}`));
 for(const name of ['DCU_activity_processed_ALU_pct','L2_hit_rate_pct','VGPR_count','SGPR_count','shared_memory_size_bytes','theoretical_occupancy_upper_bound_pct','DRAM_throughput','achieved_occupancy_pct']){const vals=[...new Set(hardware.map(r=>r[name]??'unavailable'))];box.append(elt('span',`${name}: ${vals.length?vals.join(' / '):'unavailable'}`,'metric-chip'));}
 box.append(elt('p',`FX 可见流量 ${high.traffic_bytes??'unavailable'} bytes（${high.traffic_completeness??'unavailable'}），不代表实测 HBM/DRAM 流量；理论 occupancy 上界不代表 achieved occupancy。`));const btn=elt('button','查看该实例所有硬件、分类与来源');btn.onclick=()=>{sourceDetail('high_latency_processes',high,{process:p,strict_owned_kernels:kernels,process_live:live,attachments:attach,hardware,opportunity:opp});$('details').scrollIntoView({block:'start'});};box.append(btn);tableSection(box,'该实例完整硬件属性',hardware,Object.keys(H.hardware[0]||{}),'R08 hardware');body.append(box);
 });},{denominator:`高延迟 128 / 全体 ${D.processes.length}；共 ${groups.length} 组。`,ranking:'组内全部高延迟实例的 R07 观测时长总和降序；同分按组键排序'});$('rankedRoot').append(cat.section);cat.render();
 // R08 selected hardware windows may be outside R09's high-latency subset.
 const hardwareProcesses=D.processes.filter(p=>{const families=new Set((am.get(p.process)||[]).map(a=>a.matched_kernel_family));return H.hardware.some(h=>h.event_id===p.event&&h.stage===p.stage&&families.has(h.matched_kernel_family));});
 const hardwareGroups=[...groupRows(hardwareProcesses,p=>p.phase+' / '+p.stage)].map(([key,members])=>({key,name:key,members:members.sort((a,b)=>(offset(b.e)-offset(b.b))-(offset(a.e)-offset(a.b))||a.process.localeCompare(b.process)),score:members.reduce((s,p)=>s+offset(p.e)-offset(p.b),0)})).sort((a,b)=>b.score-a.score||a.key.localeCompare(b.key));
 const hc=catalog('hardware','R08 硬件证据关联 Process：观测时间线','补充展示有精确 R08 硬件关联的 Process。它们可能不属于上方已标记高延迟子集；本栏不会重新给它们贴高延迟标签。时间线仍只使用 R07 观测。',hardwareGroups,(card,g)=>{let chooser;groupBand(card,bandEntries(g.members),i=>chooser?.selectIndex(i.index));chooser=choose(card,g,(body,p)=>{const families=new Set((am.get(p.process)||[]).map(a=>a.matched_kernel_family));const hardware=H.hardware.filter(h=>h.event_id===p.event&&h.stage===p.stage&&families.has(h.matched_kernel_family));processPlot(body,p);body.append(elt('p',`${hardware.length} 条精确关联的 R08 重放硬件属性；R09 高延迟标记：${hm.has(p.process)?'在已标记列表中':'不在已标记列表中'}。点击表行查看全部指标、单位和 unavailable 原因。`));tableSection(body,'关联硬件属性',hardware,['matched_kernel_family','hardware_evidence_class','DCU_activity_processed_ALU_pct','L2_hit_rate_pct','theoretical_occupancy_upper_bound_pct','DRAM_throughput'],'R08 hardware');const btn=elt('button','查看完整硬件与源 Process');btn.onclick=()=>{sourceDetail('process_timeline',p,{attachments:am.get(p.process),hardware});$('details').scrollIntoView({block:'start'});};body.append(btn);});},{denominator:`${hardwareProcesses.length} 个精确关联 Process，源硬件表 ${H.hardware.length} 行。`,ranking:'关联 Process 的 R07 观测时长总和降序；不使用重放耗时'});$('rankedRoot').append(hc.section);hc.render();RANKED.hardwareProcessCount=hardwareProcesses.length;
 const full=elt('section');full.append(elt('h2','完整来源与任意实例'));for(const [title,rows,fields,name] of [['全部高延迟',H.processes,['process','phase','stage','b','e','ms','live_status'],'high_latency_processes'],['全部 R08 硬件属性',H.hardware,Object.keys(H.hardware[0]),'R08 hardware'],['全部流量 / 资源关联',H.attachments,['process_range','event_id','stage','matched_kernel_family','fx_visible_total_io_bytes','resource_evidence_class'],'traffic_resource_attachment'],['全部 Process',D.processes,['process','forward','layer','phase','stage','b','e'],'process_timeline']])tableSection(full,title,rows,fields,name);$('rankedRoot').append(full);
}
function renderConcurrency(){const ks=C.kernel_concurrency.map(r=>interval(r,'kernel_concurrency','b','e')),qs=C.queue_concurrency.map(r=>interval(r,'queue_concurrency','b','e'));
 const countLanes=()=>[{label:`DCU${device} kernel 并发`,subtitle:'严格归属事件的区间扫描',device,items:ks,count:'n',maxCount:2,unit:'kernel',color:'#64b5ff'},{label:`DCU${device} queue 并发`,subtitle:'活跃队列数；不可与 kernel 相加',device,items:qs,count:'n',maxCount:1,unit:'queue',color:'#f3bd6d'}];
 const categories=[],forwards=D.rankings.concurrency.map(g=>({...g,name:g.key,score:Number(g.score_ns),members:g.members.map(id=>pmap.get(id))}));
 categories.push(catalog('concurrency','设备内并发：按 forward 排名前 20 组','单 batch、单设备 DCU1 的真实并发。每组先给出全部 Process 的梯形时间带，再在同一线性时间轴上对照 kernel 数、queue 数和原始利用率。空白不能据此认定整卡空闲。',forwards,(card,g)=>{card.append(elt('p',`${g.members.length} 个 Process；归属 kernel 忙碌并集 ${duration(g.score)}；并发 ≥2 的区间并集 ${duration(Number(g.overlap_ns))}；峰值 ${g.peak}。排名按忙碌并集，不把重叠重复计时。`));let plot;groupBand(card,bandEntries(g.members),i=>{plot?.setView(i.b,i.e);sourceDetail('process_timeline',i.p);});const b=offset(g.forward.b),e=offset(g.forward.e);const peak=ks.filter(i=>i.b<e&&i.e>b&&i.row.n>1).sort((a,b)=>(b.e-b.b)-(a.e-a.b))[0];plot=chart(card,countLanes().concat(liveLane()),[b,e],{title:g.name,focus:peak?[peak.b-10000,peak.e+10000]:null});},{denominator:`全部 ${forwards.length} 个 forward；kernel / queue 各 ${ks.length} 段。`,ranking:'forward 真实范围内 active kernel >0 的区间并集降序'}));
 const raw=normGroups('raw');categories.push(catalog('raw','原始利用率：长 Process 窗口前 20 组','按 phase + stage 分组，优先展示最长过程窗口。所有原始点保留；不连接点、不插值、不补零。没有足够原始样本的短过程仍可选择，明确显示无合格点。',raw,(card,g)=>{card.append(elt('p',`${g.members.length} 个 Process；最长 ${duration(g.score)}。这里只展示采样点，不重新估算过程均值或混合成组均值。`));let chooser;groupBand(card,bandEntries(g.members),i=>chooser?.selectIndex(i.index));chooser=choose(card,g,(body,p)=>{const b=offset(p.b),e=offset(p.e),points=samples.slice(lowerBound(samples,b),lowerBound(samples,e));body.append(elt('p',`本窗口 ${points.length} 个原始点，其中 ${points.filter(s=>s.eligible).length} 个合格；× 表示对齐不合格。没有点的位置是未知，不是 0%。`));chart(body,[marker(p),liveLane()],[b,e],{title:p.process});});},{denominator:`全部 ${D.processes.length} 个 Process，${raw.length} 组；原始点 ${samples.length}。`,ranking:'组内最长 Process 观测时长降序；不是低利用率排名'}));
 const unknown=D.rankings.unknown.map(g=>({...g,name:g.key,score:Number(g.score_ns)}));categories.push(catalog('unknown','未知采样间隔：前 20 项时间线','以相邻原始点时间差排序，不分组。标注的是两点之间没有采样点的跨度；缺少调用起止信息，不能解释成采样器停采或 GPU idle。另有 4 个对齐不合格点，可在完整表查看。',unknown,(card,g)=>{const a=C.samples[g.members[0]],b=C.samples[g.members[1]],start=offset(a.t),end=offset(b.t),pad=Math.max(1000000,Math.round((end-start)*.15));const gap={b:start,e:end,table:'derived_adjacent_sample_interval',row:{previous:a,next:b,span_ns:g.score_ns,acquisition_gap_duration:'unavailable'},unknown:true,label:'两点间无采样点'};card.append(elt('p',`[${a.t}, ${b.t}) ns；时间差 ${duration(g.score)}；端点对齐不确定度 ${a.uncertainty} / ${b.uncertainty} ns。端点状态 ${a.status} / ${b.status}。`));chart(card,[{label:'两点间未知利用率',subtitle:'并非停采时长',items:[gap],color:'#b29edb',device},liveLane()],[start-pad,end+pad],{title:g.name});},{denominator:`全部 ${unknown.length} 个正间隔；全部 ${samples.length} 个原始点。`,ranking:'相邻原始采样点的时间差降序；同分按源索引键排序'}));
 const gapmap=new Map(C.gaps.map(r=>[r.id,r]));const launch=D.rankings.launch.map(g=>({...g,name:g.key,score:Number(g.score_ns),members:g.members.map(id=>gapmap.get(id))}));categories.push(catalog('launch','Host launch gap：分组前 20 时间线','按 stage + gap kind 分组。记录的是同一 Process 内的 HIP runtime launch 间隔；不等于 kernel 间隔，更不能直接解释成 GPU idle。',launch,(card,g)=>{card.append(elt('p',`${g.members.length} 条原始间隔；组内最长 ${duration(g.score)}；查看不同实例可保留所有归属与证据状态。`));let chooser;groupBand(card,bandEntries(g.members.map(r=>({...r,process:undefined}))),i=>chooser?.selectIndex(i.index));chooser=choose(card,g,(body,r)=>{const p=pmap.get(r.process),b=offset(r.b),e=offset(r.e),pad=Math.max(1000,Math.round((e-b)*.08));body.append(elt('p',`${r.kind}；资源状态 ${r.resource_status}；${r.resource_reason}。`));const gap={...interval(r,'launch_gaps','b','e',r.kind),unknown:true};chart(body,[{label:'Host launch 间隔',subtitle:r.stage,items:[gap],color:'#bda1dd',device},...countLanes(),liveLane()],[b-pad,e+pad],{title:r.id});const btn=elt('button','查看原始 gap 与所属 Process');btn.onclick=()=>sourceDetail('launch_gaps',r,{process:p});body.append(btn);});},{denominator:`完整 ${C.gaps.length} 条 host launch gap，${launch.length} 组。`,ranking:'组内最长原始 gap duration 降序；不按组总和推断设备空闲'}));
 const tabs=elt('div',undefined,'controls rank-toolbar'),holder=elt('div');$('rankedRoot').append(tabs,holder);for(const cat of categories){const button=elt('button',cat.section.querySelector('h2').textContent.split('：')[0],'rank-tab');button.onclick=()=>{for(const b of tabs.children)b.setAttribute('aria-selected','false');button.setAttribute('aria-selected','true');holder.replaceChildren(cat.section);cat.render();};tabs.append(button);}tabs.firstChild.click();
 const full=elt('section');full.append(elt('h2','完整原始数据与自由时间窗口'));const explorer=elt('details'),ec=elt('div');explorer.append(elt('summary','展开整个观测窗口：全部 kernel / queue 并发及原始点'),ec);explorer.ontoggle=()=>{if(explorer.open&&!ec.childNodes.length)chart(ec,countLanes().concat(liveLane()),[0,offset(D.scope.display_end_ns)]);};full.append(explorer);
 for(const [title,rows,fields,table] of [['全部 kernel 并发',C.kernel_concurrency,['b','e','n','evidence','timing'],'kernel_concurrency'],['全部 queue 并发',C.queue_concurrency,['b','e','n','kernels','evidence'],'queue_concurrency'],['全部原始采样（含不合格）',C.samples,['t','mean','max','uncertainty','eligible','status'],'live_utilization_aligned'],['对齐不合格采样',C.samples.filter(r=>!r.eligible),['t','mean','max','uncertainty','status'],'live_utilization_aligned'],['全部相邻点时间间隔',D.rankings.unknown,['key','b','e','score_ns'],'derived_adjacent_sample_interval'],['全部 host launch gap',C.gaps,['id','process','kind','b','e','duration','resource_status'],'launch_gaps'],['全部依赖状态',C.dependencies,['edge_id','event_id','source_process_range','target_process_range','dependency_state','ready_time_ns','slack_ns'],'dependency_state'],['全部机会状态',C.opportunities,['process_range','event_id','stage','status','failed_gates_json','claim_boundary'],'opportunity_candidates'],['全部 Process',D.processes,['process','forward','layer','phase','stage','b','e'],'process_timeline']])tableSection(full,title,rows,fields,table);$('rankedRoot').append(full);
}
if(D.mode==='high')renderHigh();else renderConcurrency();RANKED.ready=true;RANKED.data=D;
