/* R10 presentation revision: full immutable PAYLOAD retained; ranking is navigation only. */
const RANKED={version:'r10-ranked-timeline-1',categories:{},charts:[],gapEndpointChecks:[],ready:false};window.RANKED=RANKED;
const elt=(tag,txt,cls)=>{const x=document.createElement(tag);if(txt!==undefined)x.textContent=txt;if(cls)x.className=cls;return x;};
const offset=v=>{const n=ns(v)-ns(PAYLOAD.origin_ns);if(n>BigInt(Number.MAX_SAFE_INTEGER)||n< -BigInt(Number.MAX_SAFE_INTEGER))throw Error('unsafe relative offset');return Number(n);};
const absolute=n=>String(ns(PAYLOAD.origin_ns)+BigInt(Math.round(n)));
const duration=n=>n>=1e9?(n/1e9).toFixed(3)+' s':n>=1e6?(n/1e6).toFixed(3)+' ms':n>=1e3?(n/1e3).toFixed(3)+' µs':n+' ns';
const reqName=id=>'请求 '+(String(id).match(/req-(\d+)/)?.[1]||id);
const phase=p=>p.phase||(p.forward_id?.includes('-prefill-')?'prefill':p.forward_id?.includes('-decode-')?'decode':'unknown');
const groupRows=(rows,key)=>{const m=new Map();for(const r of rows){const k=key(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r);}return m;};
function sourceDetail(table,row,extra={}){showDetails({table,table_sha256:PAYLOAD.tables[table]?.source_table_sha256,source_row_id:row.source_row_id||row.process_range_id,original_row:row,...extra});}
// Pagination controls DOM size only: every source row remains searchable and reachable.
function tableView(container,rows,fields,onSelect){let page=0,filtered=rows;const controls=elt('div',undefined,'controls');const search=elt('input',undefined,'pager-search');search.placeholder='搜索全部记录（所有字段）';const prev=elt('button','上一页'),next=elt('button','下一页'),state=elt('span',undefined,'page-count'),jump=elt('input');jump.type='number';jump.min='1';jump.value='1';jump.style.width='85px';const go=elt('button','跳页');controls.append(search,prev,next,jump,go,state);const table=elt('table'),head=elt('thead'),hr=elt('tr'),body=elt('tbody');fields.forEach(f=>hr.append(elt('th',f)));head.append(hr);table.append(head,body);container.replaceChildren(controls,table);const size=60;
 function draw(){page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1)));body.replaceChildren();for(const r of filtered.slice(page*size,(page+1)*size)){const tr=elt('tr');fields.forEach(f=>tr.append(elt('td',r[f]??'')));if(onSelect)tr.onclick=()=>onSelect(r);body.append(tr);}state.textContent=`匹配 ${filtered.length} / 全部 ${rows.length}；第 ${page+1} / ${Math.max(1,Math.ceil(filtered.length/size))} 页；每页 ${size} 行`;jump.value=String(page+1);prev.disabled=page===0;next.disabled=(page+1)*size>=filtered.length;}
 search.onchange=()=>{const s=search.value.toLowerCase();filtered=s?rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(s))):rows;page=0;draw();};prev.onclick=()=>{page--;draw();};next.onclick=()=>{page++;draw();};go.onclick=()=>{page=Math.max(0,Number(jump.value)-1);draw();};draw();container._paging={rows,get filtered(){return filtered;},get page(){return page;}};
}
function interval(row,table,begin='begin_ns',end='end_ns',label=''){return {b:offset(row[begin]),e:offset(row[end]),row,table,label};}
function lowerBound(a,n,field='b'){let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(a[m][field]<n)lo=m+1;else hi=m;}return lo;}
// Every small multiple uses linear, true R07 coordinates. Navigation never changes source intervals.
function chart(host,lanes,initial,{focus=null,shades=[],title='R07 观测时间线'}={}){const panel=elt('div');host.append(panel);const buttons=elt('div',undefined,'controls');const minus=elt('button','缩小'),plus=elt('button','放大'),reset=elt('button','完整窗口'),focusButton=elt('button','聚焦关键区间'),begin=elt('input'),end=elt('input'),jump=elt('button','跳转 ns');begin.setAttribute('aria-label','绝对开始纳秒');end.setAttribute('aria-label','绝对结束纳秒');begin.style.width=end.style.width='195px';buttons.append(plus,minus,reset);if(focus)buttons.append(focusButton);buttons.append(begin,end,jump);const state=elt('p',undefined,'chart-state'),scroll=elt('div',undefined,'chart-host'),canvas=elt('canvas'),tip=elt('div','点击矩形或采样点查看全部命中记录；滚轮缩放，拖动平移。','chart-tooltip'),hits=elt('div',undefined,'chart-hit');canvas.tabIndex=0;canvas.setAttribute('aria-label',title);scroll.append(canvas);panel.append(buttons,state,scroll,tip,hits);
 let view=initial.slice(),geometry=[],drag=null;const base=Math.floor(initial[0]),left=220,rowH=76,top=52,right=30;let w=0;
 function x(t){return left+(t-view[0])/(view[1]-view[0])*(w-left-right);}
 function commit(b,e){if(!Number.isSafeInteger(b)||!Number.isSafeInteger(e)||e<=b)throw Error('Invalid exact relative viewport');view=[b,e];draw();}
 function zoom(f,anchor=.5){const span=view[1]-view[0],next=Math.max(1,Math.round(span*f)),pivot=view[0]+Math.round(span*anchor);commit(pivot-Math.round(next*anchor),pivot-Math.round(next*anchor)+next);}
 function draw(){w=Math.max(1040,scroll.clientWidth);const h=top+lanes.length*rowH+42,dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const c=canvas.getContext('2d');c.scale(dpr,dpr);c.fillStyle='#0b1728';c.fillRect(0,0,w,h);c.font='12px system-ui';c.fillStyle='#d4e4f8';c.fillText('时间 / ms（相对本图基准；刻度线性）',left,17);geometry=[];
  for(let j=0;j<=5;j++){const t=view[0]+(view[1]-view[0])*j/5,xx=x(t);c.strokeStyle='#263b55';c.beginPath();c.moveTo(xx,36);c.lineTo(xx,h-30);c.stroke();c.fillStyle='#abc0dc';c.fillText(((t-base)/1e6).toFixed(view[1]-view[0]<1e6?6:3),Math.min(w-80,xx),34);}
  lanes.forEach((lane,li)=>{const y=top+li*rowH;c.fillStyle='#d2e4f8';c.fillText(lane.label.slice(0,31),8,y+22);c.font='11px system-ui';c.fillStyle='#96aecb';c.fillText(lane.subtitle||'',8,y+42);c.font='12px system-ui';c.strokeStyle='#263b55';c.beginPath();c.moveTo(left,y+rowH-6);c.lineTo(w-right,y+rowH-6);c.stroke();c.save();c.beginPath();c.rect(left,y,w-left-right,rowH-8);c.clip();
   for(const sh of shades){if(sh.device!==undefined&&String(sh.device)!==String(lane.device))continue;if(sh.b>=view[1]||sh.e<=view[0])continue;const xx=x(Math.max(sh.b,view[0])),xe=x(Math.min(sh.e,view[1]));c.save();c.beginPath();c.rect(xx,y,xe-xx,rowH-8);c.clip();c.fillStyle='#b89bdf35';c.fillRect(xx,y,xe-xx,rowH-8);c.strokeStyle='#9c7ec055';for(let sx=xx-rowH;sx<xe;sx+=12){c.beginPath();c.moveTo(sx,y+rowH-8);c.lineTo(sx+rowH,y);c.stroke();}c.restore();}
   let items=lane.items||[];if(lane.points)items=items.slice(lowerBound(items,view[0]),lowerBound(items,view[1]));
   if(lane.points){c.fillStyle='#9eafc8';c.fillText('100%',left+3,y+12);c.fillText('0%',left+3,y+61);}
   for(const item of items){if(lane.points){if(!Number.isFinite(item.v))continue;const xx=x(item.b),yy=y+60-item.v*.48;c.strokeStyle=item.eligible?'#54d8a8':'#c4a3e8';c.fillStyle=c.strokeStyle;c.beginPath();if(item.eligible)c.arc(xx,yy,2.3,0,Math.PI*2);else{c.moveTo(xx-3,yy-3);c.lineTo(xx+3,yy+3);c.moveTo(xx-3,yy+3);c.lineTo(xx+3,yy-3);}if(item.eligible)c.fill();else c.stroke();geometry.push({x:xx-4,y:yy-4,w:8,h:8,item,lane});continue;}
    if(item.b>=view[1]||item.e<=view[0])continue;const xx=x(Math.max(item.b,view[0])),xe=x(Math.min(item.e,view[1])),ww=xe-xx;const hh=lane.count?Math.min(48,Number(item.row[lane.count])*18+10):30;const yy=y+54-hh;c.fillStyle=lane.color||'#63b4f8';if(ww<.8){c.fillRect(xx,yy,.8,hh);}else c.fillRect(xx,yy,ww,hh);if(item.unknown){c.strokeStyle='#e3ccfa';for(let sx=xx;sx<xe;sx+=12){c.beginPath();c.moveTo(sx,yy+hh);c.lineTo(Math.min(sx+hh,xe),yy);c.stroke();}}
    const label=lane.count?`${item.row[lane.count]} ${lane.unit||'kernel'}`:item.label;if(ww>65&&label){c.save();c.beginPath();c.rect(xx,yy,ww,hh);c.clip();c.fillStyle='#051222';c.fillText(label,xx+5,yy+hh/2+4);c.restore();}geometry.push({x:xx,y:yy,w:Math.max(.8,ww),h:hh,item,lane});
   }c.restore();
  });begin.value=absolute(view[0]);end.value=absolute(view[1]);state.textContent=`基准 t0=${absolute(base)} ns（R07 原点后 ${duration(base)}）；视窗 [${begin.value}, ${end.value})；跨度 ${duration(view[1]-view[0])}。细于像素的区间以发丝标记显示，精确宽度请放大查看。`;
 }
 function matchesAt(px,py){return geometry.filter(g=>px>=g.x-2&&px<=g.x+g.w+2&&py>=g.y-2&&py<=g.y+g.h+2);}
 function inspectMatches(found){hits.replaceChildren();hits.append(elt('p',`当前点击命中 ${found.length} 条；以下无数量截断。`));for(const g of found){const i=g.item,r=i.row||window.TABLES[i.table].row(i.i),b=i.b,e=i.e;const btn=elt('button',`${g.lane.label} | ${i.label||r.source_row_id||r.sequence} | ${absolute(b)}${e!==undefined?' → '+absolute(e):''}`);btn.onclick=()=>{sourceDetail(i.table,r,{display_interval_ns:e===undefined?null:[absolute(b),absolute(e)],sampling_point_time_ns:e===undefined?absolute(b):null});$('details').scrollIntoView({block:'nearest'});};hits.append(btn);}}
 canvas.onmousemove=e=>{if(drag)return;const rc=canvas.getBoundingClientRect(),found=matchesAt(e.clientX-rc.left,e.clientY-rc.top);if(found.length){const i=found[0].item;tip.textContent=`${found[0].lane.label}；${i.label||''}；${absolute(i.b)} ns${i.e!==undefined?'，时长 '+duration(i.e-i.b):'，原始值 '+i.v+'%'}；命中 ${found.length} 条（点击查看）。`;}else tip.textContent='空白处表示本视图没有对应记录；不能据此推断设备空闲。';};canvas.onwheel=e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001),Math.max(0,Math.min(1,(e.offsetX-left)/(w-left-right))));};canvas.onpointerdown=e=>{drag={x:e.clientX,view:view.slice()};canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>3){const shift=Math.round(dx/(w-left-right)*(drag.view[1]-drag.view[0]));commit(drag.view[0]-shift,drag.view[1]-shift);}else{const rc=canvas.getBoundingClientRect();inspectMatches(matchesAt(e.clientX-rc.left,e.clientY-rc.top));}drag=null;};plus.onclick=()=>zoom(.5);minus.onclick=()=>zoom(2);reset.onclick=()=>commit(...initial);focusButton.onclick=()=>commit(...focus);jump.onclick=()=>{try{commit(offset(begin.value),offset(end.value));}catch(e){tip.textContent=e.message;}};
 const api={element:panel,lanes,get view(){return view.slice();},initial,focus,shades,draw,zoom,setView:commit,get geometry(){return geometry;},inspectMatches};RANKED.charts.push(api);draw();return api;
}
function catalog(id,title,description,groups,makeCard,{denominator,ranking}={}){const section=elt('section');section.id=id;section.append(elt('h2',title),elt('p',description),elt('p',`排名口径：${ranking}。${denominator||''}`,'rank-note'));const controls=elt('div',undefined,'controls rank-toolbar'),limit=elt('select'),start=elt('input'),go=elt('button','显示排名窗口'),select=elt('select',undefined,'rank-jump'),state=elt('span');for(const [v,t] of [['20','前 20 项 / 组']]){const o=elt('option',t);o.value=v;limit.append(o);}start.type='number';start.min='1';start.max=String(Math.max(1,groups.length));start.value='1';start.style.width='85px';select.append(elt('option','定位任意排名（完整列表）'));groups.forEach((g,i)=>{g.rank=i+1;const o=elt('option',`#${i+1} ${g.name} | ${g.members.length} 条 | ${duration(g.score)}`);o.value=String(i);select.append(o);});controls.append(elt('span','起始名次'),start,limit,go,select,state);const body=elt('div');section.append(controls,body);let visible=[];
 function render(one=null){const s=one===null?Math.max(0,Math.min(groups.length-1,(Number(start.value)||1)-1)):one,n=one!==null?1:limit.value==='all'?groups.length:20;visible=groups.slice(s,s+n);body.replaceChildren();RANKED.charts=RANKED.charts.filter(c=>c.element.isConnected);RANKED.bands=RANKED.bands.filter(b=>b.element.isConnected);state.textContent=`显示 ${visible.length} / ${groups.length} 项或组；成员 ${visible.reduce((a,g)=>a+g.members.length,0)} / ${groups.reduce((a,g)=>a+g.members.length,0)}。完整数据未截断。`;for(const g of visible){const card=elt('article',undefined,'rank-card');card.dataset.rank=String(g.rank);card.append(elt('h3',`#${g.rank} ${g.name}`));body.append(card);makeCard(card,g);} }
 go.onclick=()=>render();limit.onchange=()=>render();select.onchange=()=>{if(select.selectedIndex>0)render(Number(select.value));};RANKED.categories[id]={groups,render,get visible(){return visible;},section};return {section,render};
}
