"""CPU-gate deferred native capture startup; original model workload is unchanged."""
from pathlib import Path
import json,hashlib,shutil,os,importlib.util,types,datetime,ast
C=Path('/public/home/accl15ptg7/run_R08_R10');R=Path('/public/home/accl15ptg7/auto_trace/perf_trace_batch8/runtime/workflow01-10-fresh-e2e/batch8-dp2-fresh-003/artifacts/R08/continuation_001');B=R/'raw/runtime_tools';OLD=B/'revision_019';NEW=B/'revision_020'
def rec(p):return {'path':str(p),'size':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def save(p,x):
 with p.open('x') as f:json.dump(x,f,indent=2);f.write('\n');f.flush();os.fsync(f.fileno())
g=json.loads((B/'runtime_capture_gate_012.json').read_text());assert g['status']=='complete'
for x in g['frozen_tools']:assert rec(Path(x['path']))==x
shutil.copytree(OLD,NEW,ignore=shutil.ignore_patterns('__pycache__'))
for p in NEW.iterdir():
 if p.is_file() and p.suffix in ['.py','.sh']:p.write_text(p.read_text().replace('/revision_019/','/revision_020/'))
p=NEW/'run_capture.py';s=p.read_text();assert s.count('disabled=False')==1;s=s.replace('disabled=False','disabled=True').replace('runtime_capture_gate_012.json','runtime_capture_gate_013.json');p.write_text(s)
calls=[x for x in ast.walk(ast.parse(s)) if isinstance(x,ast.Call) and isinstance(x.func,ast.Name) and x.func.id=='collector_argv'];assert len(calls)==1 and next(k.value.value for k in calls[0].keywords if k.arg=='disabled') is True
p=NEW/'r08_pmc_gate.py';s=p.read_text().replace('native_initially_on_warmup_stop_start_reset_measured_start_terminal_stop','native_initially_off_warmup_stop_start_measured_start_terminal_stop').replace('"native_collection_initially_on": True,','"native_collection_initially_on": False,\n        "native_collection_initially_disabled": True,');p.write_text(s)
for p in NEW.glob('*.py'):compile(p.read_text(),str(p),'exec')
spec=importlib.util.spec_from_file_location('native_deferred_CPU_argv',NEW/'r08_native.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);fixture=B/'native_deferred_start_CPU_fixture_001';fixture.mkdir();argv_cases=[]
for unit in json.loads((R/'plans/r08_capture_plan.json').read_text())['physical_captures']:
 on=m.collector_argv(unit['mode'],unit['collector_kernel_name_token'],fixture,['CPU_FIXTURE_ONLY'],disabled=False);off=m.collector_argv(unit['mode'],unit['collector_kernel_name_token'],fixture,['CPU_FIXTURE_ONLY'],disabled=True);assert off.count('--pmc-off')==off.count('--trace-off')==1;assert [v for v in off if v not in ['--pmc-off','--trace-off']]==on;assert all(v in off for v in ['--hip-trace','--hiptx-trace','--trace-args','--follow-fork','--exit-cleanup']);argv_cases.append({'segment_id':unit['segment_id'],'only_added_flags':['--pmc-off','--trace-off']})
# Run the same production warmup reset fixture against the newly frozen module;
# native HIP calls stay mocked and no model imports are performed.
source=(C/'prepare_explicit_warmup_reset_019.py').read_text();start=source.index("spec=importlib.util.spec_from_file_location('warmup_reset_CPU_fixture'");end=source.index('# Core workload,',start);test=source[start:end].replace('warmup_reset_CPU_fixture','warmup_deferred_CPU_fixture').replace('warmup_reset_CPU_fixture_001','warmup_deferred_CPU_fixture_001');exec(compile(test,'<deferred-production-warmup-CPU-fixture>','exec'))
# The initial logical marker state must not activate native collection.
m._process_pid=None;no_native=[];m._hip_call=lambda op,*args:no_native.append(op);m._ensure_process_initialized();assert not no_native and not m._started
for name in ['r08_admission_order.py','r08_workload_driver.py','launch_vllm.py','source_abi_probe.py']:assert (OLD/name).read_bytes()==(NEW/name).read_bytes()
probe=B/'native_fresh_exec_pmc_write_recheck_002/RESULT.json';q=json.loads(probe.read_text());assert q['status']=='complete' and q['native_device_counts']=={'0':4,'1':4};assert '--pmc-off' in q['argv'] and '--trace-off' in q['argv']
gate={'status':'complete','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'runtime_revision':'revision_020','previous_runtime_gate':rec(B/'runtime_capture_gate_012.json'),'frozen_tools':[rec(p) for p in sorted(NEW.iterdir()) if p.is_file()],'outer_preparation':rec(Path(__file__)),'native_initial_state':'PMC and native trace disabled during model initialization; native Stop/Start immediately before each existing original warmup; existing measured Start and terminal Stop unchanged','startup_native_trace_before_original_warmups_intentionally_not_collected':True,'all_declared_measured_R06_R07_native_scopes_still_required':True,'hypothesis':'Deferring native profiler activation until initialized worker devices may avoid startup counter loss; the same initial-off flags and explicit Start work in the two-device model-free probe. Full-model root cause and effectiveness remain unproven.','root_cause_proven':False,'actual_full_model_validation_required':True,'candidate_not_activated_by_this_preparation':True,'model_free_probe':rec(probe),'CPU_fixture':{'native_device_calls':0,'all_twelve_collector_argument_cases':argv_cases,'production_capture_enables_initial_off_flags':True,'both_rank_original_warmup_reset_once_and_measured_Start_verified':True,'logical_initialization_does_not_activate_native_collection':True,'wrong_rank_and_native_Stop_failure_rejected':True},'original_two_warmups_and_eight_measured_requests_unchanged':True,'no_added_model_requests_or_model_executions':True,'observed_R07_admission_order_unchanged':True,'pre_measured_two_worker_native_health_still_required':True,'full_eight_request_and_native_attribution_audits_still_required':True,'capture_plan_sha256':rec(R/'plans/r08_capture_plan.json')['sha256'],'active_capture_interrupted':False};save(B/'runtime_capture_gate_013.json',gate);print(json.dumps({'status':'CPU_gate_complete_candidate_only','frozen_tool_count':len(gate['frozen_tools']),'argv_cases':len(argv_cases),'native_GPU_calls':0,'gate':str(B/'runtime_capture_gate_013.json')}))
