from pathlib import Path
import json
BASE=Path('/public/home/accl15ptg7/run_R08_R10/stage_tool_templates_002');p=BASE/'shared_001/cpu_stage_common.py';s=p.read_text()
s=s.replace("check(lexical.is_relative_to(sroot) and dest.is_relative_to(Path('/root')),'explicit stage bulk roots')", "check(lexical.is_relative_to(sroot) and (dest.is_relative_to(Path('/root')) or dest.is_relative_to(CONTROL.parent)),'explicit stage bulk roots')")
s=s.replace(" return maps\n\ndef storage_mappings():", " nfs=RUN/'artifacts/R08/continuation_001/authorization/NFS_output_storage_authorization_001.json'\n if nfs.exists():\n  x=read(nfs);check(x['status']=='complete' and sha(x['migration_proof']['path'])==x['migration_proof']['sha256'],'NFS correction exact proof');alias=x['original_directory_alias'];maps[Path(alias['path'])]=Path(alias['destination'])\n return maps\n\ndef storage_mappings():")
s=s.replace(" return maps,records\n\ndef validate_path(value):", " correction=CONTROL/'storage_policy_correction_001/COMPLETE.json'\n if correction.exists():\n  x=read(correction);check(x['status']=='complete' and x['R08_all_current_data_outputs_logs_physical_NFS'],'complete physical NFS correction');records.append(rec(correction))\n  for item in x['pre_R08_predecessor_relocations']:\n   key=Path(item['source_path']);check(key not in maps and item['same_bytes'] and item['canonical_link_verified'],'exact pre-R08 file backing');maps[key]=item\n  # The exact tree copy supersedes R08-only file symlinks; raw bytes and all\n  # historical authorizations remain in the NFS migration file manifest.\n  nfs=RUN/'artifacts/R08/continuation_001/authorization/NFS_output_storage_authorization_001.json'\n  if nfs.exists():\n   auth=read(nfs);check(sha(auth['file_manifest']['path'])==auth['file_manifest']['sha256'],'verified NFS source tree manifest');records.extend([rec(nfs),auth['file_manifest']]);maps={key:value for key,value in maps.items() if not key.is_relative_to(RUN/'artifacts/R08/continuation_001')}\n return maps,records\n\ndef validate_path(value):")
s=s.replace("  for lexical,dest in directories.items():\n   if q.is_relative_to(lexical):\n    check(lexical.is_symlink() and os.readlink(lexical)==str(dest),'exact authorized directory symlink');return dest/q.relative_to(lexical)\n  return q", "  seen=set()\n  while True:\n   check(q not in seen,'no directory relocation cycle');seen.add(q);changed=False\n   for lexical,dest in directories.items():\n    if q.is_relative_to(lexical):\n     check(lexical.is_symlink() and os.readlink(lexical)==str(dest),'exact authorized directory symlink');q=dest/q.relative_to(lexical);changed=True;break\n   if not changed:return q")
compile(s,str(p),'exec');p.write_text(s)
# R10 acceptance must physically live on NFS. The assigned alias is retained
# only to preserve exact renderer containment checks; no root payload backing.
p=BASE/'r10_001/build_report.py';s=p.read_text().replace("'exact empty assigned acceptance bulk entrypoint');counts", "'exact empty assigned acceptance bulk entrypoint');check(ACCEPT.stat().st_dev==assignment['NFS_filesystem_device'],'acceptance physically on NFS');counts");compile(s,str(p),'exec');p.write_text(s)
print('CPU_STAGE_NFS_TEMPLATE_VALIDATOR_PREPARED')
