/* One shared, reversible time map. Only >10% types, global pile ranking, ten time sections, resource pairs. */
const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const fmt=n=>n>=1e9?(n/1e9).toFixed(3)+' s':n>=1e6?(n/1e6).toFixed(3)+' ms':n>=1e3?(n/1e3).toFixed(3)+' µs':n+' ns';
async function decode(){const bytes=Uint8Array.from(atob($('packed').textContent.trim()),c=>c.charCodeAt(0));return JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());}
function grouped(rows,key){const out=new Map();for(const r of rows){const k=key(r);if(!out.has(k))out.set(k,[]);out.get(k).push(r);}return out;}
function lower(a,value,field){let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(field(a[m])<value)lo=m+1;else hi=m;}return lo;}
(async()=>{try{
const D=await decode(),P=new Map(D.processes.map(p=>[p.id,p])),K=grouped(D.kernels,k=>k[0]),counts=grouped(D.counts,c=>c[2]+'/'+c[3]),sampleMap=grouped(D.samples,s=>s[2]);
for(const values of counts.values())values.sort((a,b)=>a[0]-b[0]);for(const values of sampleMap.values())values.sort((a,b)=>a[0]-b[0]);
let bandwidthDirection='read',l2Peak=null,resourceFilter=MODE==='concurrency'?'hardware':'all',deviceFilter='all',skipUncovered=MODE==='concurrency';const l2Choice=new Map();
function displayResource(p){const r=D.resources[p.id];if(D.l2_reference){const ss=r.l2_samples||[],sample=ss.find(s=>s.sample_id===l2Choice.get(p.id))||ss[0]||null;return {...r,bandwidth_pct:sample&&l2Peak!==null?sample.projected_L2_GBps/l2Peak*100:null,l2_sample:sample,l2_GBps:sample?.projected_L2_GBps??null,l2_reference_GBps:l2Peak,l2_reference_source:l2Peak===null?'unavailable':'user_specified_not_verified',bandwidth_is_l2:true,bandwidth_state:sample?'retained_projection':'unavailable_no_exact_sample'};}if(D.batch8_l2&&bandwidthDirection.startsWith('l2_')){const profile=r.l2_activity;return {...r,bandwidth_pct:null,lower_metric_value:bandwidthDirection==='l2_hit'?(profile?.hit_rate_pct??null):(profile?.requests_per_second!=null?profile.requests_per_second/1e9:null),lower_metric_unit:bandwidthDirection==='l2_hit'?'%':'Grequest/s',l2_activity:profile,lower_metric_kind:bandwidthDirection,bandwidth_is_l2_activity:true,bandwidth_is_replay:true,bandwidth_state:profile?.state||'unavailable_no_l2_capture'};}if(!D.bandwidth_replay)return r;const profile=r.bandwidth_profiles?.[bandwidthDirection];return {...r,bandwidth_pct:profile?.reference_pct??null,bandwidth_direction:bandwidthDirection,bandwidth_state:profile?.state||'unavailable_no_matched_replay',bandwidth_profile:profile,bandwidth_is_replay:true};}
const reasonText={available:'有数据',short_window:'窗口过短',too_few_samples:'采样不足',sampling_gap:'采样缺口',alignment_error:'对齐无效',missing_mean:'均值缺失',not_sampled:'未采集',no_l2_sample:'无L2样本',shape_mismatch:'形状不符',invalid_counter_or_duration:'计数/耗时无效',shape_or_counter:'形状/计数不符',missing_metric:'指标缺失'};
function lowerValue(r){return r.bandwidth_is_l2_activity?r.lower_metric_value:r.bandwidth_is_l2&&l2Peak===null?r.l2_GBps:r.bandwidth_pct;}
function missingReason(r,kind){if(kind==='compute')return r.compute_state||'missing_mean';if(lowerValue(r)!==null)return 'available';if(r.bandwidth_is_l2)return 'no_l2_sample';const profile=r.bandwidth_is_l2_activity?r.l2_activity:r.bandwidth_profile;if(!profile)return 'not_sampled';return ({unavailable_shape_mismatch:'shape_mismatch',unavailable_counters_or_duration:'invalid_counter_or_duration',unavailable_shape_or_counter:'shape_or_counter'})[profile.state]||'missing_metric';}
function renderCoverage(){if(MODE!=='concurrency'||!$('coverageSummary'))return;const box=$('coverageSummary');box.replaceChildren();const schema=glyphs(selected[0]),totals=Object.fromEntries(schema.map(g=>[g.key,{label:g.label,valid:0,missing:{}}])),byType=new Map();for(const p of selected){const gs=glyphs(p),name=p.name+(p.fragment&&p.fragment!=='none'?' / '+p.fragment:' / 父过程');if(!byType.has(name))byType.set(name,{n:0,counts:{}});const row=byType.get(name);row.n++;for(const g of gs){if(g.value!==null){totals[g.key].valid++;row.counts[g.key]=(row.counts[g.key]||0)+1;}else totals[g.key].missing[g.reason]=(totals[g.key].missing[g.reason]||0)+1;}}
 box.append(el('p',`共 ${selected.length} 个入选实例；${schema.map(g=>`${g.label}有效 ${totals[g.key].valid}`).join('；')}。ε 表示采样窗口过短或样本不足的极小占位标记，值仍为未知，非实测低利用率。`));const details=el('details'),table=el('table'),tr=el('tr');for(const title of ['Process / fragment','实例数',...schema.map(g=>g.label+'有效')])tr.append(el('th',title));table.append(tr);for(const [name,row] of byType){const tr=el('tr');for(const value of [name,row.n,...schema.map(g=>row.counts[g.key]||0)])tr.append(el('td',String(value)));table.append(tr);}details.append(el('summary','各资源覆盖率和缺失原因'),table,el('pre',JSON.stringify(totals,null,2)));box.append(details);}
function glyphs(p){const r=D.resources[p.id],compute={key:'compute',label:'算',value:r.compute_pct,unit:'%',cap:100,color:'#54d6a4',reason:r.compute_state||'missing_mean'};const list=[compute];
 if(D.bandwidth_replay){for(const direction of ['read','write']){const q=r.bandwidth_profiles?.[direction],v=q?.reference_pct??null;list.push({key:direction,label:direction==='read'?'读*':'写*',value:v,unit:'%',cap:glyphCapCache[direction],color:direction==='read'?'#63b7f1':'#ebb86e',replay:true,reason:!q?'not_sampled':q.state==='unavailable_shape_mismatch'?'shape_mismatch':q.state==='unavailable_counters_or_duration'?'invalid_counter_or_duration':'missing_metric'});}}
 if(D.batch8_l2){const q=r.l2_activity;list.push({key:'l2_hit',label:'L2命中*',value:q?.hit_rate_pct??null,unit:'%',cap:100,color:'#bda3f1',replay:true,reason:q?'shape_or_counter':'not_sampled'},{key:'l2_requests',label:'L2请求*',value:q?.requests_per_second!=null?q.requests_per_second/1e9:null,unit:'Greq/s',cap:15,color:'#ed98cb',replay:true,reason:q?'shape_or_counter':'not_sampled'});}
 if(D.l2_reference){const q=displayResource(p),maxRate=glyphCapCache.l2_projected;list.push({key:'l2_projected',label:'L2*',value:l2Peak===null?q.l2_GBps:q.bandwidth_pct,unit:l2Peak===null?'GB/s':'%',cap:l2Peak===null?maxRate:Math.max(100,maxRate/l2Peak*100),color:'#bda3f1',replay:true,reason:'no_l2_sample'});}
 return list.map(g=>({...g,epsilon:g.value===null&&['short_window','too_few_samples'].includes(g.reason)}));}
const glyphCapCache={read:100,write:100,l2_projected:1500};for(const r of Object.values(D.resources)){for(const d of ['read','write'])glyphCapCache[d]=Math.max(glyphCapCache[d],r.bandwidth_profiles?.[d]?.reference_pct||0);for(const q of r.l2_samples||[])glyphCapCache.l2_projected=Math.max(glyphCapCache.l2_projected,q.projected_L2_GBps);}
function scaleHeight(g){return g.value===null?null:24*g.value/g.cap;}
function validResourceFilter(p){const gs=glyphs(p),n=gs.filter(g=>g.value!==null).length;return resourceFilter==='all'||resourceFilter==='hardware'&&gs.some(g=>g.key!=='compute'&&g.value!==null)||resourceFilter==='any'&&n>0||resourceFilter==='both'&&n===gs.length;}
const absolute=t=>String(BigInt(D.origin_ns)+BigInt(Math.round(t))),offset=t=>{const x=BigInt(t)-BigInt(D.origin_ns);if(x>BigInt(Number.MAX_SAFE_INTEGER)||x< -BigInt(Number.MAX_SAFE_INTEGER))throw Error('时间超出精确范围');return Number(x);};
let activeGroups=D.groups;
const selected=D.groups.flatMap(g=>g.piles.flatMap(c=>c.members.map(id=>P.get(id)))),extent=[D.time_sections[0][0],D.time_sections[9][1]];
let folded=true,cap=0,segments=[],coverageIntervals=[],foldFactor=1;
const endpoints=[...new Set([...extent,...selected.flatMap(p=>[p.b,p.e])])].sort((a,b)=>a-b),durations=selected.map(p=>p.d).sort((a,b)=>a-b),baseCap=durations[Math.floor(durations.length/2)]*2;
function rebuildFolds(factor=foldFactor){foldFactor=factor;cap=Math.max(1,Math.round(baseCap*factor));
 coverageIntervals=[];const candidates=selected.filter(p=>(deviceFilter==='all'||p.device===deviceFilter)&&(MODE==='high'||validResourceFilter(p))).sort((a,b)=>a.b-b.b||a.e-b.e);
 for(const p of candidates){const last=coverageIntervals.at(-1);if(last&&p.b<=last[1])last[1]=Math.max(last[1],p.e);else coverageIntervals.push([p.b,p.e]);}
 let sum=0,j=0;segments=[];for(let i=0;i<endpoints.length-1;i++){const b=endpoints[i],e=endpoints[i+1];while(j<coverageIntervals.length&&coverageIntervals[j][1]<=b)j++;const covered=j<coverageIntervals.length&&coverageIntervals[j][0]<=b&&coverageIntervals[j][1]>=e,skipped=skipUncovered&&!covered,weight=skipped?0:folded?Math.min(e-b,cap):e-b;
  if(skipped&&segments.at(-1)?.skipped){segments.at(-1).e=e;continue;}
  segments.push({b,e,u:sum,v:sum+weight,weight,skipped,ratio:weight?(e-b)/weight:null});sum+=weight;
 }}rebuildFolds();
function project(t){if(!folded&&!skipUncovered)return t;const i=Math.min(segments.length-1,Math.max(0,lower(segments,t,s=>s.e))),s=segments[i];if(t<s.b)return s.u+t-s.b;if(t>s.e)return s.v+t-s.e;return s.u+(t-s.b)/(s.e-s.b)*s.weight;}
function inverse(u){if(!folded&&!skipUncovered)return u;let i=Math.min(segments.length-1,Math.max(0,lower(segments,u,s=>s.v)));while(i<segments.length-1&&segments[i].v<=u)i++;const s=segments[i];if(u<s.u)return s.b+u-s.u;if(u>s.v)return s.e+u-s.v;if(s.weight===0)return s.e;return s.b+(u-s.u)/s.weight*(s.e-s.b);}
function timeDistance(a,b){if(!folded&&!skipUncovered)return b-a;if(b<a)return -timeDistance(b,a);const i=Math.min(segments.length-1,Math.max(0,lower(segments,a,s=>s.e))),s=segments[i];if(a>=s.b&&b<=s.e)return (b-a)*s.weight/(s.e-s.b);return project(b)-project(a);}
function advance(t,delta){if(!folded&&!skipUncovered)return t+delta;const i=Math.min(segments.length-1,Math.max(0,lower(segments,t,s=>s.e))),s=segments[i];if(s.weight>0){const candidate=t+delta*(s.e-s.b)/s.weight;if(t>=s.b&&t<=s.e&&candidate>=s.b&&candidate<=s.e)return candidate;}return inverse(project(t)+delta);}
let sectionIndex=Math.max(0,Math.min(9,Number(new URLSearchParams(location.search).get('section')||1)-1));
let view=D.time_sections[sectionIndex].slice(),width=0,height=0,geometry=[],envelopes=[],selectedId=null,drag=null,lastPointer=null,highOnly=false;
const left=340,right=30,canvas=$('timeline'),axis=$('axis'),tracks=[],groupBoxes=[];
// Within a pile use overlap sublanes, without moving the shared x coordinates.
function layout(){tracks.length=0;let y=0;for(const [rank,entry] of D.pile_order.entries()){const g=D.groups.find(g=>g.name===entry.group),pile=g.piles.find(c=>c.rank===entry.pile_rank),members=pile.members.map(id=>P.get(id)).sort((a,b)=>a.b-b.b||a.e-b.e||a.id.localeCompare(b.id)),layoutMembers=MODE==='high'?members:members.filter(p=>validResourceFilter(p)&&(deviceFilter==='all'||p.device===deviceFilter)),ends=[],slot=new Map();if(MODE==='concurrency'&&!layoutMembers.length)continue;for(const p of layoutMembers){let lane=ends.findIndex(end=>end<=p.b);if(lane<0)lane=ends.length;ends[lane]=p.e;slot.set(p.id,lane);}const step=MODE==='concurrency'?glyphs(layoutMembers[0]).length*40+16:24,h=MODE==='high'?174:Math.max(100,16+ends.length*step);tracks.push({g,pile,members,slot,y,h,step,rank:rank+1,subLanes:ends.length});y+=h;}height=Math.max(50,y);$('status').textContent=`全部 Process 累计时长 ${fmt(D.total_process_ns)}（逐实例求和，不扣并发）。仅 ${D.groups.length} 种类型超过10%；显示 ${tracks.length}/${D.pile_order.length} 堆，原始堆排名保留。`;document.querySelector('h1 span').textContent=`${tracks.length} 堆 · 全局排序`;canvas.setAttribute('aria-label',`${tracks.length}堆共轴${MODE==='high'?'执行时间':'计算和带宽利用率'}分布`);}layout();
const controls=$('controls'),minus=el('button','缩小 ×2'),plus=el('button','放大 ×2'),full=el('button','本段完整范围'),prev=el('button','← 平移'),next=el('button','平移 →'),begin=el('input'),end=el('input'),jump=el('button','跳转 ns');begin.id='beginNs';end.id='endNs';begin.setAttribute('aria-label','公共时间轴绝对开始纳秒');end.setAttribute('aria-label','公共时间轴绝对结束纳秒');controls.append(plus,minus,full,prev,next,el('span','起止 ns'),begin,end,jump);const foldButton=el('button','取消折叠 · 恢复线性'),strength=el('input'),foldInfo=el('button','查看全部折叠区间');foldButton.id='foldToggle';strength.id='foldStrength';strength.type='range';strength.min='0';strength.max='100';strength.value='50';strength.style.width='100px';strength.setAttribute('aria-label','折叠强度');controls.append(foldButton,el('span','折叠强度'),strength,foldInfo);foldButton.onclick=()=>{folded=!folded;foldButton.textContent=folded?'取消折叠 · 恢复线性':'启用公共时间轴折叠';rebuildFolds();draw();};strength.oninput=()=>{rebuildFolds(10**((50-Number(strength.value))/25));draw();};foldInfo.onclick=()=>{$('details').hidden=false;const body=$('detailBody');body.replaceChildren(el('h3','所有轨道共用的折叠区间'),el('p','» 表示已跳过的无可显示数据区间，其时间宽度为0；// 表示压缩但保留的区间。所有轨道共用该映射，绝对时间戳不变。'));jsonBox(body,'全部压缩区间（未截断）',segments.filter(s=>s.skipped||s.ratio>1).map(s=>({skipped_no_visible_data:s.skipped,begin_ns:absolute(s.b),end_ns:absolute(s.e),real_duration_ns:s.e-s.b,display_weight_ns:s.weight,compression_ratio:s.ratio})));};
const sectionSelect=el('select'),sectionPrev=el('button','上一段'),sectionNext=el('button','下一段');sectionSelect.id='timeSection';sectionPrev.id='previousSection';sectionNext.id='nextSection';for(let i=0;i<10;i++){const o=el('option',`第 ${i+1}/10 段 · ${fmt(D.time_sections[i][0])} – ${fmt(D.time_sections[i][1])}`);o.value=i;sectionSelect.append(o);}controls.prepend(sectionPrev,sectionSelect,sectionNext);
function chooseSection(i){sectionIndex=Math.max(0,Math.min(9,i));if(MODE==='concurrency'&&skipUncovered){const available=D.time_sections.map((s,j)=>coverageIntervals.some(w=>w[0]<s[1]&&w[1]>s[0])?j:-1).filter(j=>j>=0);if(available.length&&!available.includes(sectionIndex))sectionIndex=available.find(j=>j>=sectionIndex)??available.at(-1);}view=D.time_sections[sectionIndex].slice();sectionSelect.value=sectionIndex;sectionPrev.disabled=sectionIndex===0;sectionNext.disabled=sectionIndex===9;for(const a of document.querySelectorAll('nav a'))if(a.getAttribute('href').includes('TIMELINE.html')||a.getAttribute('href')==='CONCURRENCY_UTILIZATION.html')a.href=a.href.split('?')[0]+'?section='+(sectionIndex+1);draw();}
sectionSelect.onchange=()=>chooseSection(Number(sectionSelect.value));sectionPrev.onclick=()=>chooseSection(sectionIndex-1);sectionNext.onclick=()=>chooseSection(sectionIndex+1);
const nav=$('navigation'),groupSelect=el('select'),pileSelect=el('select'),memberSelect=el('select'),focus=el('button','定位实例（全部轨道同步）'),device=el('select');groupSelect.id='groupSelect';pileSelect.id='pileSelect';memberSelect.id='memberSelect';device.id='deviceFilter';
function groupOptions(){groupSelect.replaceChildren();for(const g of activeGroups.filter(g=>tracks.some(t=>t.g.rank===g.rank))){const o=el('option',`#${g.rank} ${g.name} · ${(g.share*100).toFixed(2)}%`);o.value=g.rank;groupSelect.append(o);}}groupOptions();function pileOptions(){pileSelect.replaceChildren();for(const t of tracks.filter(t=>t.g.rank===Number(groupSelect.value)).sort((a,b)=>a.pile.rank-b.pile.rank)){const o=el('option',`堆 ${t.pile.rank}`);o.value=t.pile.rank;pileSelect.append(o);}}pileOptions();for(const d of ['all',...new Set(D.processes.map(p=>p.device))]){const o=el('option',d==='all'?'全部设备':'DCU'+d);o.value=d;device.append(o);}
nav.append(groupSelect,pileSelect,memberSelect,focus,device);const note=el('span',MODE==='high'?'蓝色 DCU0 / 橙色 DCU1；红色边缘=原高延迟标记':'每个实例同时包含各资源子矩形，高度连续对应数值');if(MODE==='concurrency'&&D.l2_reference)note.textContent='上方：计算活跃率（%）；下方：L2投影吞吐量（GB/s，或相对用户基准占比）';note.style.fontSize='12px';nav.append(note);
if(MODE==='concurrency'&&D.bandwidth_replay)nav.append(el('span','各实例同时显示：算%、读*%、写*%、L2命中*%、L2请求* Greq/s；* 是重放属性，非同次R07实测。'));
if(MODE==='concurrency'&&D.l2_reference){
 const samples=selected.flatMap(p=>D.resources[p.id].l2_samples||[]),chooser=el('select'),peak=el('input'),apply=el('button','应用 L2 基准'),state=el('span');chooser.id='l2Sample';peak.id='l2Peak';apply.id='applyL2Peak';state.id='l2State';peak.type='number';peak.min='0';peak.placeholder='L2 基准 GB/s（可留空）';peak.setAttribute('aria-label','用户指定L2参考带宽GB/s');chooser.append(el('option','选择 L2 样本并定位（不合并不同族）'));for(const s of samples){const p=P.get(s.process_range),o=el('option',`${p.phase} L${p.layer} ${p.name} / ${s.kernel_family} · ${s.projected_L2_GBps.toFixed(2)} GB/s`);o.value=s.sample_id;chooser.append(o);}chooser.onchange=()=>{const s=samples.find(s=>s.sample_id===chooser.value);if(s){l2Choice.set(s.process_range,s.sample_id);focusProcess(P.get(s.process_range));}};
 function updateState(){state.textContent=l2Peak===null?'L2高度与GB/s成正比，基准为空时不计算百分比。':`L2高度与相对用户基准 ${l2Peak} GB/s 的投影占比成正比；不是实测利用率。`;}
 apply.onclick=()=>{const v=peak.value.trim();if(v!==''&&(!Number.isFinite(Number(v))||Number(v)<=0)){state.textContent='L2 基准必须为正数；留空恢复 GB/s。';return;}l2Peak=v===''?null:Number(v);updateState();draw();};nav.append(chooser,peak,apply,state);updateState();
}
if(MODE==='concurrency'){const legend=el('span');legend.id='glyphLegend';nav.append(legend);}
if(MODE==='concurrency'){const filter=el('select');filter.id='resourceFilter';for(const [v,t] of [['hardware','仅已关联的硬件资源窗口'],['all','恢复全部实例及缺失标记'],['any','隐藏未采集/未关联，仅保留有资源的实例'],['both','仅显示所有资源均有效']]){const o=el('option',t);o.value=v;filter.append(o);}filter.value=resourceFilter;filter.onchange=()=>{resourceFilter=filter.value;layout();groupOptions();pileOptions();members();rebuildFolds();chooseSection(sectionIndex);};nav.append(filter);const gaps=el('button','恢复无资源时间区间');gaps.id='skipUncovered';gaps.onclick=()=>{skipUncovered=!skipUncovered;gaps.textContent=skipUncovered?'恢复无资源时间区间':'跳过无资源时间区间';rebuildFolds();draw();};nav.append(gaps);}
function members(){const t=tracks.find(t=>t.g.rank===Number(groupSelect.value)&&t.pile.rank===Number(pileSelect.value));memberSelect.replaceChildren();focus.disabled=!t;if(!t)return;for(const id of t.pile.members){const p=P.get(id);if(MODE==='concurrency'&&(!validResourceFilter(p)||deviceFilter!=='all'&&p.device!==deviceFilter))continue;const o=el('option',`${p.device==='0'?'DCU0':'DCU1'} ${p.phase} L${p.layer} · ${fmt(p.d)}${p.high?' · 高延迟':''}`);o.value=id;memberSelect.append(o);}if([...memberSelect.options].some(o=>o.value===t.pile.representative))memberSelect.value=t.pile.representative;}
groupSelect.onchange=()=>{pileOptions();members();};pileSelect.onchange=members;members();
function x(t){const span=timeDistance(view[0],view[1]);return span>0?left+timeDistance(view[0],t)/span*(width-left-right):left;}
function commit(b,e){if(!Number.isSafeInteger(b)||!Number.isSafeInteger(e)||e<=b)throw Error('请输入有效、递增的整数纳秒范围');const bounds=D.time_sections[sectionIndex];b=Math.max(b,bounds[0]);e=Math.min(e,bounds[1]);if(e<=b)return;view=[b,e];draw();}
function zoom(f,anchor=.5){const old=timeDistance(view[0],view[1]);if(old<=0)return;const span=old*f,pivot=advance(view[0],old*anchor),b=Math.round(advance(pivot,-span*anchor)),e=Math.round(advance(pivot,span*(1-anchor)));commit(b,Math.max(b+1,e));}
function focusProcess(p){selectedId=p.id;chooseSection(Math.min(9,D.time_sections.findIndex(s=>p.b>=s[0]&&p.b<s[1])));const pad=Math.max(1,Math.round(p.d*.3));commit(p.b-pad,p.e+pad);const t=tracks.find(t=>t.slot.has(p.id));if(!t)return;window.scrollTo({top:Math.max(0,canvas.getBoundingClientRect().top+window.scrollY+t.y-(document.querySelector('.sticky-axis')?.getBoundingClientRect().height||230)-24),behavior:'instant'});}
focus.onclick=()=>focusProcess(P.get(memberSelect.value));device.onchange=()=>{deviceFilter=device.value;layout();groupOptions();pileOptions();members();rebuildFolds();chooseSection(sectionIndex);};plus.onclick=()=>zoom(.5);minus.onclick=()=>zoom(2);full.onclick=()=>commit(...D.time_sections[sectionIndex]);prev.onclick=()=>{const d=Math.round((view[1]-view[0])*.6);commit(view[0]-d,view[1]-d);};next.onclick=()=>{const d=Math.round((view[1]-view[0])*.6);commit(view[0]+d,view[1]+d);};jump.onclick=()=>{try{commit(offset(begin.value),offset(end.value));}catch(e){$('viewState').textContent=e.message;}};
function utilLevel(v){return v===null||!Number.isFinite(v)||v<0||v>100?null:v<=25?1:v<=50?2:v<=75?3:4;}
function canvasContext(c,h){const dpr=Math.min(window.devicePixelRatio||1,2);c.width=Math.round(width*dpr);c.height=Math.round(h*dpr);c.style.height=h+'px';const ctx=c.getContext('2d');ctx.scale(dpr,dpr);return ctx;}
function truncate(c,text,max){if(c.measureText(text).width<=max)return text;while(text.length&&c.measureText(text+'…').width>max)text=text.slice(0,-1);return text+'…';}
function draw(){renderCoverage();if($('glyphLegend'))$('glyphLegend').textContent='连续高度比例尺：24px = '+glyphs(selected[0]).map(g=>g.label+' '+g.cap.toFixed(2)+' '+g.unit).join('；')+'。0只画基线，ε为未知占位。';width=Math.max(720,canvas.parentElement.clientWidth);const c=canvasContext(canvas,height),a=canvasContext(axis,44);geometry=[];envelopes=[];c.fillStyle='#101d2e';c.fillRect(0,0,width,height);a.fillStyle='#142236';a.fillRect(0,0,width,44);a.font='12px system-ui';a.fillStyle='#c8dcf0';a.fillText(`Process / 时长堆（${tracks.length} 条轨道）`,12,18);a.fillText((folded?'公共折叠时间轴（// 为压缩区间）':'公共线性时间轴')+' · 真实时间 / s',left,13);
 const ticks=6;for(let i=0;i<=ticks&&timeDistance(view[0],view[1])>0;i++){const time=advance(view[0],timeDistance(view[0],view[1])*i/ticks),xx=x(time);c.strokeStyle='#273a50';c.beginPath();c.moveTo(xx,0);c.lineTo(xx,height);c.stroke();a.fillStyle='#a8c3df';a.font='11px system-ui';a.fillText((time/1e9).toFixed(view[1]-view[0]<1e6?9:view[1]-view[0]<1e9?6:3),Math.min(width-78,xx),34);}
 if(folded||skipUncovered){let lastMark=-100;for(const s of segments){if((!s.skipped&&s.ratio<=1)||s.e<=view[0]||s.b>=view[1])continue;const b=x(Math.max(s.b,view[0])),e=x(Math.min(s.e,view[1])),mid=(b+e)/2;c.fillStyle='#a998d009';c.fillRect(b,0,e-b,height);if(mid-lastMark>32){a.fillStyle='#d3b4fa';a.font='bold 13px system-ui';a.fillText(s.skipped?'»':'//',mid,44);lastMark=mid;}}}
 for(const {g,y} of groupBoxes){c.fillStyle='#1b3048';c.fillRect(0,y,width,44);c.font='bold 13px system-ui';c.fillStyle='#deebfa';c.fillText(truncate(c,`#${g.rank}  ${g.name}`,width-500),12,y+18);c.font='11px system-ui';c.fillStyle='#9cb6d0';c.fillText(`${g.count} 实例 · 累计 ${fmt(g.total_ns)} / ${(g.share*100).toFixed(2)}% · 原高延迟 ${g.high_count} 个 · 父过程/fragment 可重叠`,12,y+35);}
 for(const t of tracks){c.fillStyle='#132237';c.fillRect(0,t.y,left-1,t.h-2);c.strokeStyle='#33475d';c.beginPath();c.moveTo(0,t.y+t.h-2);c.lineTo(width,t.y+t.h-2);c.stroke();c.font='bold 12px system-ui';c.fillStyle='#d7e6f6';c.fillText(truncate(c,`#${t.rank} ${t.g.name} · 堆${t.pile.rank}`,left-22),12,t.y+18);c.font='11px system-ui';c.fillStyle='#c3d5e8';c.fillText(`堆总时长 ${fmt(t.pile.total_ns)} · ${t.members.length} 实例`,12,t.y+36);c.fillStyle='#94afca';c.fillText(`单次 ${fmt(t.pile.min_ns)} – ${fmt(t.pile.max_ns)}`,12,t.y+54);c.fillText(`类型占比 ${(t.g.share*100).toFixed(2)}% · 高延迟 ${t.pile.high_count}`,12,t.y+72);
  c.save();c.beginPath();c.rect(left,t.y,width-left-right,t.h-3);c.clip();
  if(MODE==='high'){
   const ps=t.members.filter(p=>p.b<view[1]&&p.e>view[0]&&(deviceFilter==='all'||p.device===deviceFilter));
   if(ps.length){const n=ps.length,ys=i=>t.y+24+(n===1?60:i/(n-1)*120),ends=ps.map(p=>[x(Math.max(p.b,view[0])),x(Math.min(p.e,view[1]))]);const top=t.y+18,bottom=t.y+150,fs=ps.map((_,i)=>(ys(i)-top)/(bottom-top));let ls=n>1?(ends[n-1][0]-ends[0][0])/(fs[n-1]-fs[0]):0,rs=n>1?(ends[n-1][1]-ends[0][1])/(fs[n-1]-fs[0]):0;const li=Math.min(...ends.map((z,i)=>z[0]-ls*fs[i]))-4,ri=Math.max(...ends.map((z,i)=>z[1]-rs*fs[i]))+4,points=[[li,top],[ri,top],[ri+rs+8,bottom],[li+ls-8,bottom]];
    c.fillStyle='#5ca4df18';c.strokeStyle='#779ab6';c.lineWidth=1;c.beginPath();points.forEach(([xx,yy],i)=>i?c.lineTo(xx,yy):c.moveTo(xx,yy));c.closePath();c.fill();c.stroke();envelopes.push({rank:t.rank,points,memberCount:n});
    ps.forEach((p,i)=>{const [xx,xe]=ends[i],yy=ys(i),ww=xe-xx;c.strokeStyle=p.high?'#ff8894':p.device==='0'?'#6dbcf4':'#efc06e';c.lineWidth=p.id===selectedId?2:1;c.beginPath();c.moveTo(xx,yy);c.lineTo(ww<.4?xx+.4:xe,yy);c.stroke();if(n<=8&&ww>90){c.fillStyle='#d2e7fa';c.font='10px system-ui';c.fillText(`${fmt(p.d)} · DCU${p.device}`,xx+2,yy-3);}geometry.push({id:p.id,p,track:t,x:xx,y:yy-1,w:ww,h:2,resource:null,actualWidth:x(p.e)-x(p.b),subpixel:ww<1});});
   }c.restore();continue;
  }
  for(const p of t.members){if(p.b>=view[1]||p.e<=view[0]||!validResourceFilter(p)||(deviceFilter!=='all'&&p.device!==deviceFilter))continue;const xx=x(Math.max(p.b,view[0])),xe=x(Math.min(p.e,view[1])),ww=xe-xx,yy=t.y+12+t.slot.get(p.id)*t.step,color=p.device==='0'?(p.phase==='prefill'?'#69b7f2':'#69d0d2'):(p.phase==='prefill'?'#edb467':'#dfd075');
   if(!validResourceFilter(p))continue;const resource=displayResource(p),gs=glyphs(p),rectHeight=gs.length*40+4,glyphGeometry=[];
   // Missing resource rows remain blank; the Process scope is available in details.
   gs.forEach((g,i)=>{if(resourceFilter!=='all'&&g.value===null&&!g.epsilon)return;const base=yy+34+i*40,hh=scaleHeight(g),reason=reasonText[g.reason]||'未知';let drawnHeight=hh;
    if(g.value===null){drawnHeight=g.epsilon?1:4;c.strokeStyle=g.epsilon?'#c4b785':'#8290a0';c.setLineDash(g.epsilon?[]:[3,3]);c.beginPath();c.moveTo(xx,base);c.lineTo(xe,base);c.stroke();c.setLineDash([]);if(g.epsilon){c.fillStyle='#c4b785';c.fillRect(xx,base-1,Math.min(3,ww),1);}}
    else if(hh===0){c.strokeStyle=g.color;c.beginPath();c.moveTo(xx,base);c.lineTo(xe,base);c.stroke();}
    else{c.fillStyle=g.color;c.fillRect(xx,base-hh,ww,hh);if(g.replay){c.strokeStyle='#d6c1eb';c.setLineDash([3,2]);c.strokeRect(xx,base-hh,ww,hh);c.setLineDash([]);}}
    if(ww>46){c.save();c.beginPath();c.rect(xx,yy+i*40-5,ww,40);c.clip();c.font='10px system-ui';c.fillStyle='#d7e5f3';c.fillText(`${g.label} ${g.value===null?(g.epsilon?'ε 非实测':reason):g.value.toFixed(2)+' '+g.unit}`,xx+2,base-Math.max(hh||0,4)-3);c.restore();}
    glyphGeometry.push({...g,x:xx,y:base-(hh||0),w:ww,proportionalHeight:hh,markerHeight:g.value===null?drawnHeight:null});
   });
   if(p.id===selectedId){c.strokeStyle='#fff';c.strokeRect(xx-1,yy-2,Math.max(1,ww)+2,rectHeight+4);}
   geometry.push({id:p.id,p,track:t,x:xx,y:yy,w:ww,h:rectHeight,resource:resource,glyphs:glyphGeometry,actualWidth:x(p.e)-x(p.b),subpixel:ww<1});
  }c.restore();
 }
 const omitted=segments.filter(s=>s.skipped&&s.e>view[0]&&s.b<view[1]).reduce((n,s)=>n+Math.min(s.e,view[1])-Math.max(s.b,view[0]),0);if(timeDistance(view[0],view[1])<=0){a.fillStyle='#c8dcf0';a.fillText('本段没有符合筛选的资源数据；此时间段已跳过',left,32);}
 begin.value=absolute(view[0]);end.value=absolute(view[1]);$('viewState').textContent=`${folded?'共同折叠轴，长区段权重上限 '+fmt(cap)+'，按真实端点标刻度':'共同线性轴'} · 第 ${sectionIndex+1}/10 段 · 公共视窗 [${begin.value}, ${end.value}) ns · 真实跨度 ${fmt(view[1]-view[0])} · 当前可见 ${geometry.length} 个实例 / ${tracks.length} 条轨道 · 资源筛选 ${resourceFilter} · » 已跳过无可显示数据 ${fmt(omitted)}（非设备空闲；不改变分堆）。Ctrl/Shift+滚轮全局缩放；横向拖动平移；点击查看。`;
}
function hits(event){const r=canvas.getBoundingClientRect(),xx=event.clientX-r.left,yy=event.clientY-r.top;return geometry.filter(g=>yy>=g.y-2&&yy<=g.y+g.h+2&&xx>=g.x-1&&xx<=g.x+Math.max(1,g.w)+1);}
canvas.onmousemove=e=>{if(drag)return;const hs=hits(e);canvas.title=hs.length?`${hs.length} 个命中；${hs[0].p.name} / ${fmt(hs[0].p.d)} / DCU${hs[0].p.device}\n${absolute(hs[0].p.b)} → ${absolute(hs[0].p.e)} ns${hs[0].subpixel?'\n竖线为不足1像素的存在标记，请放大':''}${MODE==='concurrency'?'\n'+glyphs(hs[0].p).map(g=>g.label+'：'+(g.value===null?(g.epsilon?'ε（非实测）':reasonText[g.reason]||'未知'):g.value.toFixed(2)+' '+g.unit)).join('；'):''}`:'';};canvas.onwheel=e=>{if(e.ctrlKey||e.shiftKey){e.preventDefault();zoom(Math.exp(e.deltaY*.001),Math.max(0,Math.min(1,(e.offsetX-left)/(width-left-right))));}};canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,view:view.slice()};canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>5&&Math.abs(dx)>Math.abs(dy)){const shift=dx/(width-left-right)*(project(drag.view[1])-project(drag.view[0])),b=Math.round(inverse(project(drag.view[0])-shift)),e=Math.round(inverse(project(drag.view[1])-shift));commit(b,Math.max(b+1,e));}else if(Math.abs(dx)<=5&&Math.abs(dy)<=5){const hs=hits(e);if(hs.length)inspect(hs);}drag=null;};canvas.onpointercancel=()=>{drag=null;};
function jsonBox(host,title,value){const d=el('details'),summary=el('summary',title),pre=el('pre',JSON.stringify(value,null,2));d.append(summary,pre);host.append(d);}
function inspect(hs){$('details').hidden=false;const body=$('detailBody');body.replaceChildren();if(hs.length>1){const choose=el('select');for(const h of hs){const o=el('option',`${h.p.name} DCU${h.p.device} L${h.p.layer} ${fmt(h.p.d)}`);o.value=h.id;choose.append(o);}choose.onchange=()=>show(P.get(choose.value),target);body.append(el('p',`该像素命中 ${hs.length} 个真实实例；全部可选，无截断。`),choose);}const target=el('div');body.append(target);show(hs[0].p,target);}
function show(p,body){selectedId=p.id;draw();body.replaceChildren();body.append(el('h3',p.name),el('p',`DCU${p.device} · ${p.phase} · L${p.layer} · ${p.request} · fragment=${p.fragment||'none'}`),el('p',`真实执行时长 ${fmt(p.d)}（${p.d} ns）\n[${absolute(p.b)}, ${absolute(p.e)}) ns`),el('p',p.high?'属于原先已标记的高延迟实例。':'不属于原先已标记的高延迟实例；本次未重新分类。'));const focus=el('button','放大此实例所在时间段（所有轨道同步）');focus.onclick=()=>{$('details').hidden=true;focusProcess(p);};body.append(focus);
 const ks=K.get(p.id)||[],ss=sampleMap.get(p.device)||[],lo=lower(ss,p.b,s=>s[0]),hi=lower(ss,p.e,s=>s[0]),segs=counts.get(p.device+'/kernel')||[];let peak=0,overlap=0,busy=0;for(let i=lower(segs,p.b,s=>s[1]);i<segs.length&&segs[i][0]<p.e;i++){const s=segs[i],n=Math.max(0,Math.min(p.e,s[1])-Math.max(p.b,s[0]));peak=Math.max(peak,s[4]);if(s[4]>0)busy+=n;if(s[4]>=2)overlap+=n;}
 body.append(el('p',`严格归属 kernel ${ks.length} 个；本设备观测 kernel 峰值 ${peak}；窗口内 busy 并集 ${fmt(busy)}，并发≥2 并集 ${fmt(overlap)}。该并发来自本设备全部已归属 kernel，并非仅此 Process。`),el('p',`窗口内原始采样点 ${hi-lo} 个；原始点不作插值。硬件旁证 ${(D.metrics[p.id]||[]).length} 条；缺少匹配时为 unavailable。`));
 jsonBox(body,'资源数值、L2样本与基准、重放方向和缺失原因',displayResource(p));
 jsonBox(body,'原始高延迟分类与过程可用性',{classification:D.classifications[p.id]||null,availability:D.availability[p.id]||null});jsonBox(body,'全部严格归属 kernel（精确原始起止）',ks.map(k=>({id:k[6],name:k[5],queue:k[4],begin_ns:absolute(k[1]),end_ns:absolute(k[2]),duration_ns:k[2]-k[1]})));jsonBox(body,'全部硬件属性（R08重放旁证，不是R07耗时）',D.metrics[p.id]||[]);jsonBox(body,'原始采样点与对齐状态',ss.slice(lo,hi).map(s=>({timestamp_ns:absolute(s[0]),value:s[1],eligible:s[3],uncertainty_ns:s[4]})));jsonBox(body,'精确源定位与归档校验',{process:p,origin_ns:D.origin_ns,source_pages:D.source});
}
$('closeDetail').onclick=()=>{$('details').hidden=true;};window.addEventListener('resize',draw);chooseSection(sectionIndex);
window.PILES={data:D,tracks,extent,glyphs,scaleHeight,get envelopes(){return envelopes;},lowerValue,missingReason,get resourceFilter(){return resourceFilter;},get l2Peak(){return l2Peak;},displayResource,get bandwidthDirection(){return bandwidthDirection;},utilLevel,chooseSection,get sectionIndex(){return sectionIndex;},get view(){return view.slice();},get activeGroups(){return activeGroups;},get geometry(){return geometry;},project:x,timeProject:project,timeInverse:inverse,timeDistance,get folded(){return folded;},get segments(){return segments;},get skipUncovered(){return skipUncovered;},get coverageIntervals(){return coverageIntervals;},setView:commit,zoom,focus:focusProcess,inspect,draw,ready:true};window.PAGE_READY=true;
}catch(e){$('status').textContent='页面加载失败：'+e.message;window.PAGE_ERROR=e.stack;throw e;}})();
