"""Independent terminal R09 audit of accepted bytes and full conservation proof."""
from cpu_stage_common import *

def main():
 assignment=read(ROOT/'authorization/assignment.json');check(assignment['runtime_goal']=='R09' and assignment['predecessor_stages']==['R%02d'%i for i in range(1,9)],'complete assigned prefix');check(target_state()==assignment['target'],'unchanged target');manifest=read(ROOT/'artifact_manifest.json')
 for x in manifest['files']:verify(x)
 accepted=read(ROOT/'analysis/fresh_e2e_analysis.accepted.json');candidate=read(ROOT/'analysis/fresh_e2e_analysis.json');audit=read(ROOT/'validation/R09_TABLE_INDEPENDENT_AUDIT.json');check(accepted['status']=='complete' and candidate['status']=='candidate_complete_pending_independent_audit','accepted candidate transition')
 for k,v in candidate.items():
  if k!='status':check(accepted[k]==v,'accepted analysis does not alter candidate '+k)
 check(audit['status']=='complete' and audit['analysis_manifest_sha256']==sha(ROOT/'analysis/fresh_e2e_analysis.json') and audit['all_tables_complete'] and audit['all_eight_requests_have_exact_phase_process_and_kernel_coverage'],'full independent twelve-table audit')
 names=['request_timeline','process_timeline','kernel_timeline','live_utilization_aligned','process_live_utilization','kernel_concurrency','queue_concurrency','launch_gaps','high_latency_processes','dependency_state','traffic_resource_attachment','opportunity_candidates'];check([x['logical_name'] for x in accepted['tables']]==names,'ordered twelve-table denominator');check(accepted['row_universes']['requests']==8 and accepted['row_universes']['processes']==12544 and accepted['row_universes']['strict_owned_kernels']==23660,'source universes');check(accepted['row_universes']['live_samples']==2491806 and accepted['row_universes']['live_gaps']==800 and accepted['row_universes']['live_anchors']==2,'all raw utilization retained');check(not accepted['sampling_performed'] and not accepted['replay_timing_used_as_latency'] and not accepted['report_or_visualization_generated'],'CPU analysis boundary')
 lineage=read(ROOT/'R09_SOURCE_LINEAGE.json');check(all(v is False for v in lineage['execution_boundaries'].values()),'stage execution boundaries')
 save(ROOT/'R09_COMPLETION_AUDIT.json',{'schema_version':1,'status':'complete','execution_status':'complete','evidence_status':'complete','runtime_goal':'R09','runtime_run_id':RUN_ID,'lineage_id':RUN_ID,'trace_profile_sha256':PROFILE,'coverage_target_met':True,'next_authorization_required':False,'independent_audit':True,'builder_imported':False,'artifact_manifest':rec(ROOT/'artifact_manifest.json'),'source_lineage':rec(ROOT/'R09_SOURCE_LINEAGE.json'),'full_request_analysis':rec(ROOT/'analysis/fresh_e2e_analysis.accepted.json'),'table_audit':rec(ROOT/'validation/R09_TABLE_INDEPENDENT_AUDIT.json'),'row_universes':accepted['row_universes'],'all_eight_request_phase_process_kernel_coverage_verified':True,'replay_timing_used_as_latency':False,'R07_original_native_controller_terminal_claimed':False,'cpu_only':True,'auditor':rec(Path(__file__)),'completed_utc':now()});print('R09_COMPLETION_AUDIT_COMPLETE',flush=True)
if __name__=='__main__':main()
