"""Seal closed render/browser outputs before the independent terminal auditor."""
from cpu_stage_common import *
import sys
from html.parser import HTMLParser
PAGES=['index.html','E2E_PROCESS_TIMELINE.html','E2E_PROCESS_TIMELINE_LOSSLESS.html','HIGH_LATENCY_PROCESS_HARDWARE_TIMELINE.html','CONCURRENCY_UTILIZATION.html','E2E_PROCESS_TIMELINE.full.perfetto.json','full_timeline_manifest.json']
class Navigation(HTMLParser):
 def __init__(self):super().__init__();self.links=[]
 def handle_starttag(self,tag,attrs):
  a=dict(attrs)
  if tag=='a' and 'href' in a:self.links.append(a['href'])
def main():
 assignment=read(ROOT/'authorization/assignment.json');check(assignment['runtime_goal']=='R10','assigned R10');accept=ROOT/'acceptance';manifest=read(accept/'full_timeline_manifest.json');browser_path=ROOT/'validation/BROWSER_ACCEPTANCE.json';browser=read(browser_path);check(browser['status']=='complete' and browser['network_attempt_count']==0 and browser['all_browser_processes_closed_before_result'],'browser checkpoint complete')
 target=target_state();check(target==assignment['target'],'source bytes unchanged since assignment');analysis=read(assignment['r09_analysis']['path']);verify(assignment['r09_analysis'])
 for phase in ['render','browser']:
  record=read(ROOT/'validation/phase_lifecycle'/f'{phase}.json');check(record['status']=='complete' and record['all_started_processes_terminated'],'prior closed stage subprocesses')
 presentation=[{**rec(accept/name),'content_type':'text/html' if name.endswith('.html') else 'application/json','role':name} for name in PAGES];navigation=[];parser=Navigation();parser.feed((accept/'index.html').read_text())
 declared=[accept/'offline_acceptance_manifest.json',ROOT/'R10_SOURCE_LINEAGE.json',ROOT/'R10_COMPLETION_AUDIT.json']
 for link in parser.links:
  check(':' not in link and not link.startswith('//'),'relative entrypoint link');target_path=Path(os.path.abspath(accept/link));check(target_path.is_relative_to(ROOT),'contained navigation');check(target_path.exists() or target_path in declared,'declared complete navigation');navigation.append({'href':link,'resolved_target':str(target_path),'status_at_sealing':'exists' if target_path.exists() else 'declared_following_sealing_step'})
 offline={'schema_version':1,'status':'complete','evidence_status':'complete','runtime_goal':'R10','runtime_run_id':RUN_ID,'lineage_id':RUN_ID,'trace_profile_sha256':PROFILE,'presentation_payload':presentation,'navigation_graph':navigation,'completion_audit_declared_path':str(ROOT/'R10_COMPLETION_AUDIT.json'),'browser_acceptance':rec(browser_path),'event_count':manifest['expected_event_count'],'network_attempt_count':browser['network_attempt_count'],'full_event_formula':manifest['event_count_formula'],'pages':manifest['pages'],'all_required_interactions':next(x['checks'] for x in browser['pages'] if x['page']['path'].endswith('E2E_PROCESS_TIMELINE_LOSSLESS.html')),'minimum_viewport_ns':1,'evidence_legend_classes':['observed R07 timing','observed live utilization','replay_projected R08 hardware attributes','derived analysis','unavailable/unknown evidence'],'replay_timing_used_as_latency':False,'sampling_performed':False,'unavailable_as_zero_presented':False,'speedup_or_proven_causality_claimed':False,'sealing_order':'presentation -> browser -> offline manifest -> source lineage -> pre-audit artifact manifest -> independent completion audit -> outer handoff','sealer':rec(Path(__file__)),'sealing_utc':now()}
 save(accept/'offline_acceptance_manifest.json',offline)
 boundaries={key:False for key in ['model_execution_performed','gpu_dcu_execution_performed','device_query_performed','profiler_execution_performed','trace_collection_performed','pmc_collection_performed','replay_performed','external_network_contacted','target_mutation_performed','predecessor_mutation_performed','successor_execution_performed','nested_skill_execution_performed','adapt_goal_execution_performed']}
 lineage={'schema_version':1,'runtime_goal':'R10','runtime_branch':'workflow01-10-fresh-e2e','runtime_run_id':RUN_ID,'lineage_id':RUN_ID,'trace_profile_sha256':PROFILE,'target':target,'selected_request':assignment['selected_request'],'workload':assignment['workload'],'topology':assignment['topology'],'predecessor_stages':assignment['predecessor_stages'],'predecessor_handoffs':assignment['predecessor_handoffs'],'cumulative_runtime_ledger':assignment['cumulative_runtime_ledger'],'predecessor_transitive_validation':assignment['predecessor_transitive_validation'],'r09_analysis':assignment['r09_analysis'],'r09_tables':analysis['tables'],'consumed_sources':assignment['consumed_sources'],'observed_clock_source':'R07 only','replay_attribute_source':'R08 audited native per-dispatch replay_projected attributes; observed shape differences block direct comparison','derived_analysis_source':'R09 accepted twelve tables only','replay_timing_used_as_latency':False,'offline_acceptance_manifest':rec(accept/'offline_acceptance_manifest.json'),'presentation_payload':presentation,'full_timeline_manifest':rec(accept/'full_timeline_manifest.json'),'browser_acceptance':rec(browser_path),'renderer_tools':manifest['tools'],'browser_binary':browser['browser_binary'],'interpreter':manifest['interpreter'],'execution_boundaries':boundaries,'source_revision_history':assignment['frozen_tool_history'],'phase_lifecycle':[rec(ROOT/'validation/phase_lifecycle'/f'{phase}.json') for phase in ['render','browser']],'assignment':rec(ROOT/'authorization/assignment.json'),'sealer':rec(Path(__file__)),'sealed_utc':now(),'same_run_R07_recovery_exception_preserved':True,'remote_publishing_owned_by_separate_outer_scheduler':True}
 lineage.update(prefix_hash_fields(assignment))
 save(ROOT/'R10_SOURCE_LINEAGE.json',lineage)
 # Acyclic: final audit and separately assigned handoff seal this manifest.
 files=[]
 for p in sorted(set(ROOT.rglob('*'))|set(accept.rglob('*'))):
  if p.is_file() and '__pycache__' not in p.parts and p.name not in ['artifact_manifest.json','artifact_manifest.preaudit.json','R10_COMPLETION_AUDIT.json'] and not p.name.endswith('.log'):files.append(rec(p))
 save(ROOT/'artifact_manifest.preaudit.json',{'schema_version':1,'runtime_goal':'R10','runtime_run_id':RUN_ID,'lineage_id':RUN_ID,'files':files,'excludes':['this manifest','later independent R10_COMPLETION_AUDIT.json','outer scheduler handoff','live stdout/stderr logs sealed separately at outer handoff'],'nine_pre_audit_business_deliverables_complete':True,'completion_audit_path':str(ROOT/'R10_COMPLETION_AUDIT.json')})
 print('R10_PREAUDIT_SEAL_COMPLETE',len(files),flush=True)
if __name__=='__main__':main()
