'use strict';
const $=id=>document.getElementById(id);
const text=(node,value)=>{node.textContent=String(value);};
const ns=v=>{if(!/^-?\d+$/.test(String(v)))throw Error('Invalid decimal nanoseconds');return BigInt(v);};
const formatNs=v=>Number(v)>1e9?(Number(v)/1e9).toFixed(4)+' s':String(v)+' ns';
const htmlEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function decodeBlock(value){const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(new TextDecoder().decode(await new Response(stream).arrayBuffer()));}
async function loadTables(){const out={};for(const [name,pack] of Object.entries(PAYLOAD.tables)){const data=[];for(const encoded of pack.blocks){const chunk=await decodeBlock(encoded);for(const row of chunk)data.push(row);}out[name]={fields:pack.fields,constants:pack.constants,data,sourceRowHashes:pack.source_row_hashes,row(i){const x={...this.constants};this.fields.forEach((f,j)=>x[f]=this.data[i][j]);return x;},rows(){return this.data.map((_,i)=>this.row(i));}};}return out;}
function showDetails(value){text($('details'),JSON.stringify(value,null,2));}
function tableView(container,rows,fields,onSelect){const table=document.createElement('table');const head=document.createElement('thead');head.innerHTML='<tr>'+fields.map(f=>'<th>'+htmlEscape(f)+'</th>').join('')+'</tr>';table.append(head);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const f of fields){const td=document.createElement('td');text(td,row[f]??'');tr.append(td);}if(onSelect)tr.onclick=()=>onSelect(row);body.append(tr);}table.append(body);container.replaceChildren(table);}
function coverage(tables){const requests=tables.request_timeline.rows();const processes=tables.process_timeline?.rows()||[];const kernels=tables.kernel_timeline?.rows()||[];const data=requests.map(r=>({request_id:r.request_id,rank:r.rank,device:r.physical_device_id,completion_tokens:r.completion_tokens,processes:tables.process_timeline?processes.filter(p=>p.request_id===r.request_id).length:PAYLOAD.coverage.find(x=>x.request_id===r.request_id).process_targets,kernels:tables.kernel_timeline?kernels.filter(k=>k.request_id===r.request_id).length:PAYLOAD.coverage.find(x=>x.request_id===r.request_id).strict_owned_kernels,prefill:tables.process_timeline?processes.filter(p=>p.request_id===r.request_id&&p.phase==='prefill').length:PAYLOAD.coverage.find(x=>x.request_id===r.request_id).phases.find(x=>x.phase==='prefill').observed_process_targets,decode:tables.process_timeline?processes.filter(p=>p.request_id===r.request_id&&p.phase==='decode').length:PAYLOAD.coverage.find(x=>x.request_id===r.request_id).phases.find(x=>x.phase==='decode').observed_process_targets,duration:formatNs(ns(r.duration_ns))}));if($('coverage'))tableView($('coverage'),data,['request_id','rank','device','completion_tokens','processes','prefill','decode','kernels','duration']);return data;}
function parseJson(v){return typeof v==='string'?JSON.parse(v):v;}
function timeline(tables){
 const req=tables.request_timeline.rows(),proc=tables.process_timeline.rows(),kern=tables.kernel_timeline.rows();
 const origin=ns(PAYLOAD.origin_ns);const byRequest=new Map(req.map(r=>[r.request_id,r]));const byProcess=new Map(proc.map(r=>[r.process_range_id,r]));const sourceTables=new Map(PAYLOAD.source_tables.map(t=>[t.logical_name,t]));
 const sourceHashes=new Map();for(const name of ['request_timeline','process_timeline','kernel_timeline']){const table=tables[name];table.rows().forEach((r,i)=>sourceHashes.set(name+':'+(r.kernel_instance_id||r.process_range_id||r.request_id),table.sourceRowHashes[i]));}
 const events=[],contexts=[];const seenContext=new Set();let nextTrack=0;const trackMap=new Map();
 function add(row,kind,id,track,table,copy=0,context=false,sourceParent=null){const b=ns(row.begin_ns),e=ns(row.end_ns);if(e<b)throw Error('Negative interval');const request=byRequest.get(row.request_id);const rb=ns(request.begin_ns);const event={id,source_id:row.kernel_instance_id||row.process_range_id||row.runtime_call_id||row.range_id||row.request_id,kind,track,copy,begin_ns:String(b),end_ns:String(e),begin:b-origin,end:e-origin,request_relative_begin_ns:String(b-rb),request_relative_end_ns:String(e-rb),request_id:row.request_id,rank:row.rank??row.dp_rank,device:row.physical_device_id??row.native_device,process:row.process_id||'',layer:row.layer_idx||'',phase:row.phase||'',family:row.native_kernel_name||row.process_id||'',event:row.native_kernel_name||row.process_id||kind,evidence:'observed R07 timing',source_table:table,source_table_sha256:sourceTables.get(table)?.sha256,source_row_sha256:sourceHashes.get(table+':'+(sourceParent||row.kernel_instance_id||row.process_range_id||row.request_id)),source_parent_row_id:sourceParent,source_hash_scope:context?'canonical owning process source row containing this exact nested context; nested original identity retained':'canonical complete source row',source_row_id:row.kernel_instance_id||row.process_range_id||row.runtime_call_id||row.range_id||row.request_id,original:row};(context?contexts:events).push(event);}
 for(const r of req)add(r,'request','request:'+r.request_id,'request / '+r.request_id,'request_timeline');
 for(const p of proc){add(p,'process','process:'+p.process_range_id,'process / '+p.request_id+' / '+p.phase+' / L'+p.layer_idx+' / '+p.process_id+' / '+p.fragment_id,'process_timeline');const ctx=parseJson(p.layer_forward_context);for(const [kind,rows] of Object.entries(ctx))for(const x of rows){const id=kind+':'+x.range_id;if(!seenContext.has(id)){seenContext.add(id);add(x,kind,id,kind+' / '+x.request_id+' / '+x.forward_id+(kind==='layer'?' / L'+x.layer_idx:''),'process_timeline',0,true,p.process_range_id);}}
  const fields=parseJson(p.hip_runtime_context_schema);for(const values of parseJson(p.hip_runtime_context)){const r={request_id:p.request_id,rank:p.rank,physical_device_id:p.physical_device_id,process_id:p.process_id,layer_idx:p.layer_idx,phase:p.phase};fields.forEach((f,i)=>r[f]=values[i]);add(r,'HIP runtime','runtime:'+r.runtime_call_id,'HIP runtime / rank '+r.rank+' / tid '+r.tid,'process_timeline',0,true,p.process_range_id);}}
 for(const k of kern){add(k,'strict_owned_kernel','kernel-owner:'+k.kernel_instance_id,'kernel owner / '+k.owner_process_range_id,'kernel_timeline',0);add(k,'gpu_queue','kernel-queue:'+k.kernel_instance_id,'queue / rank '+k.rank+' / device '+k.physical_device_id+' / queue '+k.queue_id+' / stream '+k.stream_id,'kernel_timeline',1);}
 if(events.length!==Number(PAYLOAD.expected_event_count))throw Error('Full event count mismatch');
 const all=events.concat(contexts);all.sort((a,b)=>a.begin<b.begin?-1:a.begin>b.begin?1:a.end<b.end?-1:a.end>b.end?1:a.id.localeCompare(b.id));
 const laneEnds=new Map();for(const e of all){const ends=laneEnds.get(e.track)||[];let lane=ends.findIndex(end=>end<=e.begin);if(lane<0)lane=ends.length;ends[lane]=e.end;laneEnds.set(e.track,ends);e.base_track=e.track;e.overlap_sub_lane=lane;e.track+=' / lane '+lane;}
 const idMap=new Map(all.map(e=>[e.id,e]));const extent=[0n,req.reduce((v,r)=>ns(r.end_ns)>v?ns(r.end_ns):v,origin)-origin];let view=extent.slice();let history=[view.slice()],historyIndex=0;let selected=[];let visible=all;const filters={};let density=true;
 function filtered(e){return Object.entries(filters).every(([k,v])=>String(e[k]??'').toLowerCase().includes(v.toLowerCase()));}
 function commit(begin,end,remember=true){if(end<=begin)end=begin+1n;view=[begin,end];if(remember){history=history.slice(0,historyIndex+1);history.push(view.slice());historyIndex=history.length-1;}draw();}
 function zoom(factor,anchor=.5){const span=view[1]-view[0];const next=BigInt(Math.max(1,Math.round(Number(span)*factor)));const offset=BigInt(Math.round(Number(span)*anchor));const nextOffset=BigInt(Math.round(Number(next)*anchor));const pivot=view[0]+offset;commit(pivot-nextOffset,pivot-nextOffset+next);}
 function matching(begin=view[0],end=view[1]){return visible.filter(e=>e.begin<end&&begin<e.end);}
 function list(items,label){selected=items;text($('listCount'),label+'：'+items.length+' 条；不设结果上限');const list=$('eventList');list.replaceChildren();const fragment=document.createDocumentFragment();for(const e of items){const item=document.createElement('div');item.className='event-item';text(item,e.kind+' | '+e.request_id+' | '+e.event+' | ['+e.begin_ns+', '+e.end_ns+') | '+e.id);item.onclick=()=>inspect(e.id);fragment.append(item);}list.append(fragment);}
 function inspect(id){const e=idMap.get(id);if(!e)throw Error('Unknown original event ID');showDetails({...e,begin:String(e.begin),end:String(e.end),kernel_display_copies_non_additive:e.kind==='gpu_queue'||e.kind==='strict_owned_kernel'});return e;}
 function locate(id){const e=inspect(id);for(const input of document.querySelectorAll('[data-filter]'))input.value='';Object.keys(filters).forEach(k=>delete filters[k]);visible=all;commit(e.begin,e.end>e.begin?e.end:e.begin+1n);const index=trackMap.get(e.track);if(index!==undefined)$('plotScroll').scrollTop=index*24;draw();return e;}
 function draw(){
  const canvas=$('timelineCanvas'),scroller=$('plotScroll');const width=Math.max(700,scroller.clientWidth);const height=600;canvas.width=width;canvas.height=height;const c=canvas.getContext('2d');c.clearRect(0,0,width,height);const labelWidth=240;const plotWidth=width-labelWidth;const span=view[1]-view[0];if(span<1n||span>BigInt(Number.MAX_SAFE_INTEGER))throw Error('Viewport span not safely representable after BigInt subtraction');
  trackMap.clear();const tracks=[...new Set(visible.map(e=>e.track))];tracks.forEach((t,i)=>trackMap.set(t,i));$('trackSpacer').style.height=Math.max(0,tracks.length*24-height)+'px';const top=Math.floor(scroller.scrollTop/24);const count=Math.ceil(height/24);c.fillStyle='#9fb0c8';c.font='11px system-ui';for(let i=top;i<Math.min(tracks.length,top+count);i++){const y=(i-top)*24;c.fillText(tracks[i].slice(0,38),5,y+15);c.strokeStyle='#24364e';c.beginPath();c.moveTo(labelWidth,y+23);c.lineTo(width,y+23);c.stroke();}
  const hits=matching();for(const e of hits){const ti=trackMap.get(e.track);if(ti<top||ti>=top+count)continue;const b=e.begin<view[0]?view[0]:e.begin;const en=e.end>view[1]?view[1]:e.end;const x=labelWidth+Number(b-view[0])/Number(span)*plotWidth;const w=Math.max(.5,Number(en-b)/Number(span)*plotWidth);c.fillStyle=e.kind==='gpu_queue'?'#5c8ec9':e.kind==='HIP runtime'?'#b9abd9':e.kind==='process'?'#64b5ff':'#5488ba';c.globalAlpha=density&&w<1?.35:.8;c.fillRect(x,(ti-top)*24+3,w,17);}c.globalAlpha=1;
  text($('viewState'),'原点 '+origin+' ns；绝对视窗 ['+(origin+view[0])+', '+(origin+view[1])+')；跨度 '+span+' ns；完整主事件 '+events.length+'；完整上下文 '+contexts.length+'；过滤后 '+visible.length+'；视窗内 '+hits.length+'；轨道 '+tracks.length+'；活动过滤 '+JSON.stringify(filters)+'；历史 '+historyIndex+'/'+(history.length-1));$('jumpBegin').value=String(origin+view[0]);$('jumpEnd').value=String(origin+view[1]);
 }
 for(const input of document.querySelectorAll('[data-filter]'))input.oninput=()=>{filters[input.dataset.filter]=input.value;visible=all.filter(filtered);draw();};
 $('fitFilter').onclick=()=>{if(!visible.length)return;commit(visible.reduce((a,e)=>e.begin<a?e.begin:a,visible[0].begin),visible.reduce((a,e)=>e.end>a?e.end:a,visible[0].end));};$('resetView').onclick=()=>commit(...extent);$('zoomIn').onclick=()=>zoom(.5);$('zoomOut').onclick=()=>zoom(2);$('backView').onclick=()=>{if(historyIndex>0){historyIndex--;commit(...history[historyIndex],false);}};$('forwardView').onclick=()=>{if(historyIndex<history.length-1){historyIndex++;commit(...history[historyIndex],false);}};
 $('jumpView').onclick=()=>commit(ns($('jumpBegin').value)-origin,ns($('jumpEnd').value)-origin);$('listViewport').onclick=()=>list(matching(),'完整视窗结果');$('locateEvent').onclick=()=>locate($('eventId').value);$('toggleDensity').onclick=()=>{density=!density;draw();};$('plotScroll').onscroll=draw;
 const canvas=$('timelineCanvas');canvas.onwheel=e=>{e.preventDefault();const rect=canvas.getBoundingClientRect();zoom(Math.exp(e.deltaY*.001),Math.max(0,Math.min(1,(e.clientX-rect.left-240)/(canvas.width-240))));};let drag=null;canvas.onpointerdown=e=>{drag={x:e.clientX,view:view.slice(),shift:e.shiftKey};canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!drag)return;const dx=e.clientX-drag.x;const span=drag.view[1]-drag.view[0];if(Math.abs(dx)<3){const rect=canvas.getBoundingClientRect();const pixel=Math.max(0,e.clientX-rect.left-240);const begin=view[0]+BigInt(Math.floor(pixel/(canvas.width-240)*Number(span)));const end=begin+BigInt(Math.max(1,Math.ceil(Number(span)/(canvas.width-240))));list(matching(begin,end),'点击时间像素所有交集');}else if(drag.shift){const rect=canvas.getBoundingClientRect();const x1=Math.max(0,Math.min(drag.x,e.clientX)-rect.left-240);const x2=Math.max(x1+1,Math.max(drag.x,e.clientX)-rect.left-240);commit(drag.view[0]+BigInt(Math.floor(x1/(canvas.width-240)*Number(span))),drag.view[0]+BigInt(Math.ceil(x2/(canvas.width-240)*Number(span))));}else{const move=BigInt(Math.round(dx/(canvas.width-240)*Number(span)));commit(drag.view[0]-move,drag.view[1]-move);}drag=null;};
 window.TIMELINE={events,contexts,all,idMap,get view(){return view.map(String)},get history(){return history.map(x=>x.map(String))},get historyIndex(){return historyIndex},get filters(){return {...filters}},get selected(){return selected},setView:(b,e)=>commit(ns(b)-origin,ns(e)-origin),zoom,locate,inspect,matching:()=>matching(),listViewport:()=>list(matching(),'完整视窗结果'),filter:(key,value)=>{filters[key]=value;visible=all.filter(filtered);draw();},fit:()=>$('fitFilter').click(),reset:()=>$('resetView').click(),back:()=>$('backView').click(),forward:()=>$('forwardView').click(),pan:n=>commit(view[0]+ns(n),view[1]+ns(n))};draw();
}
function hardware(tables){const high=tables.high_latency_processes.rows();const processes=new Map(tables.process_timeline.rows().map(r=>[r.process_range_id,r]));const kernels=tables.kernel_timeline.rows();const metrics=tables.traffic_resource_attachment.rows();const live=new Map(tables.process_live_utilization.rows().map(r=>[r.process_range_id,r]));text($('classificationState'),'完整高延迟分类 '+high.length+' 条，保留全局/同组 p95 的全部并列；全体过程 '+processes.size+' 条。点击任一行查看该过程的观测区间、kernel 和完整硬件指标。');tableView($('highRows'),high,['request_id','rank','process_range_id','phase','process_id','fragment_id','duration_ns','global_p95_ns','peer_p95_ns','peer_denominator'],r=>{const p=processes.get(r.process_range_id);showDetails({classification:r,observed_process:p,observed_kernels:kernels.filter(k=>k.owner_process_range_id===r.process_range_id),observed_live_utilization:live.get(r.process_range_id),replay_and_static_hardware_metrics:metrics.filter(m=>m.r07_process_range_id===r.process_range_id),interpretation:'R08 replay_projected attributes are separate observations; unavailable stays unknown; different runtime shapes cannot support direct comparison; no causality or speedup claim'});});window.HARDWARE={high,processes,kernels,metrics,live};}
function concurrency(tables){const live=tables.live_utilization_aligned;const groups={0:[],1:[]};const gaps=[];const anchors=[];const origin=ns(PAYLOAD.origin_ns);for(let i=0;i<live.data.length;i++){const r=live.row(i);if(r.record_kind==='sample')groups[r.native_device].push({index:i,offset:Number(ns(r.sample_midpoint_realtime_ns)-origin),value:Number(r.se_active_cu_pct),eligible:r.timing_eligible==='True'});else if(r.record_kind==='gap')gaps.push(r);else anchors.push(r);}
 const ks=tables.kernel_concurrency.rows(),qs=tables.queue_concurrency.rows(),launch=tables.launch_gaps.rows(),pl=tables.process_live_utilization.rows();const req=tables.request_timeline.rows();let view=[0,Math.max(...req.map(r=>Number(ns(r.end_ns)-origin)))];
 function draw(){const canvas=$('liveCanvas');canvas.width=Math.max(900,canvas.parentElement.clientWidth);canvas.height=500;const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);const width=canvas.width-100;const span=view[1]-view[0];c.font='12px system-ui';c.fillStyle='#e8eef8';
  for(const d of [0,1]){const top=30+d*230;c.fillText('设备 '+d+' — observed live utilization（原始采样点）',5,top);c.strokeStyle='#3f526d';c.strokeRect(65,top+15,width,170);for(const sample of groups[d]){if(sample.offset<view[0]||sample.offset>=view[1])continue;const x=65+(sample.offset-view[0])/span*width;const y=top+185-sample.value*1.7;c.fillStyle=sample.eligible?'#54d8a8':'#c4a3e8';c.fillRect(x,y,1,2);}for(const gap of gaps.filter(g=>Number(g.native_device)===d)){const anchor=anchors.find(a=>a.anchor_name==='start');const offset=ns(anchor.anchor_realtime_ns)-ns(anchor.anchor_monotonic_midpoint_ns);const b=Number(ns(gap.gap_begin_monotonic_ns)+offset-origin);const e=Number(ns(gap.gap_end_monotonic_ns)+offset-origin);if(b>=view[1]||e<=view[0])continue;const x=65+(Math.max(b,view[0])-view[0])/span*width;const w=Math.max(1,(Math.min(e,view[1])-Math.max(b,view[0]))/span*width);c.fillStyle='#c4a3e855';c.fillRect(x,top+15,w,170);}c.fillStyle='#e8eef8';}
  text($('liveState'),'完整原始采样 '+(groups[0].length+groups[1].length)+'；设备0 '+groups[0].length+'，设备1 '+groups[1].length+'；间隙 '+gaps.length+'；锚点 '+anchors.length+'。仅绘制原始点，不插值、不补零；间隙显示为未知。');}
 $('liveApply').onclick=()=>{const b=Number(ns($('liveBegin').value)-origin),e=Number(ns($('liveEnd').value)-origin);if(e<=b)throw Error('Invalid live viewport');view=[b,e];draw();};$('liveBegin').value=String(origin);$('liveEnd').value=String(origin+BigInt(Math.floor(view[1])));
 $('inspectSample').onclick=()=>{const i=Number($('sampleIndex').value);if(!Number.isInteger(i)||i<0||i>=live.data.length)throw Error('Sample index outside complete table');showDetails({row_index:i,...live.row(i)});};
 tableView($('unionRows'),PAYLOAD.derived_scope_summaries||[],['scope_type','scope_id','rank','physical_device_id','selected_kernel_union_duration_ns','peak_selected_kernel_concurrency','evidence_scope'],showDetails);
 tableView($('kernelConcurrencyRows'),ks,['scope_type','scope_id','rank','begin_ns','end_ns','active_kernel_count','active_queue_count'],showDetails);tableView($('queueConcurrencyRows'),qs,['scope_type','scope_id','rank','begin_ns','end_ns','active_kernel_count','active_queue_count'],showDetails);tableView($('launchGapRows'),launch,['request_id','rank','queue_id','gap_ns','overlap_ns','previous_kernel_instance_id','next_kernel_instance_id'],showDetails);tableView($('processAvailabilityRows'),pl,['request_id','rank','process_range_id','se_active_cu_pct_mean','timing_eligible_sample_count','intersecting_gap_count','availability_state'],showDetails);tableView($('samplingGapRows'),gaps,['native_device','previous_sequence','next_sequence','gap_begin_monotonic_ns','gap_end_monotonic_ns','unobserved_gap_ns'],showDetails);draw();window.CONCURRENCY={live,groups,gaps,anchors,kernelSegments:ks,queueSegments:qs,launchGaps:launch,processAvailability:pl};}
(async()=>{try{const tables=await loadTables();window.TABLES=tables;const matrix=coverage(tables);if(matrix.length!==8)throw Error('Eight-request coverage gate');if(PAYLOAD.mode==='timeline')timeline(tables);else if(PAYLOAD.mode==='hardware')hardware(tables);else if(PAYLOAD.mode==='concurrency')concurrency(tables);text($('loading'),'离线数据已完整加载并通过请求数检查。');window.PAGE_READY=true;}catch(error){text($('loading'),'验收失败：'+error.message);window.PAGE_ERROR=error.message;throw error;}})();
